//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moedelo.AccountingV2.Dto.FinancialOperations.Legacy {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FinancialOperationNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FinancialOperationNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Moedelo.AccountingV2.Dto.FinancialOperations.Legacy.FinancialOperationNames", typeof(FinancialOperationNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Агентские поступления.
        /// </summary>
        public static string AgentIncomingOperation {
            get {
                return ResourceManager.GetString("AgentIncomingOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комиссия банка.
        /// </summary>
        public static string BankFeeOutgoingOperation {
            get {
                return ResourceManager.GetString("BankFeeOutgoingOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бюджетный платеж.
        /// </summary>
        public static string BudgetaryPaymentOperation {
            get {
                return ResourceManager.GetString("BudgetaryPaymentOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Платежное поручение для бюджетного платежа.
        /// </summary>
        public static string BudgetaryPaymentOrderOperation {
            get {
                return ResourceManager.GetString("BudgetaryPaymentOrderOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выручка по кассе или БСО.
        /// </summary>
        public static string CashIncomingOperation {
            get {
                return ResourceManager.GetString("CashIncomingOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Взнос собственных средств.
        /// </summary>
        public static string ContributionOfOwnFundsOperation {
            get {
                return ResourceManager.GetString("ContributionOfOwnFundsOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поступление от покупки/продажи валюты.
        /// </summary>
        public static string CurrencyPurchaseAndSaleIncomingOperation {
            get {
                return ResourceManager.GetString("CurrencyPurchaseAndSaleIncomingOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Покупка/продажа валюты.
        /// </summary>
        public static string CurrencyPurchaseAndSaleOutgoingOperation {
            get {
                return ResourceManager.GetString("CurrencyPurchaseAndSaleOutgoingOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выплата дивидендов.
        /// </summary>
        public static string DividendPaymentOperation {
            get {
                return ResourceManager.GetString("DividendPaymentOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комиссия платежной системы .
        /// </summary>
        public static string ElectronicOutgoingOperation {
            get {
                return ResourceManager.GetString("ElectronicOutgoingOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выплата подотчётному лицу.
        /// </summary>
        public static string GetMoneyForEmployeeOperation {
            get {
                return ResourceManager.GetString("GetMoneyForEmployeeOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Платежное поручение для оплаты контрагенту.
        /// </summary>
        public static string KontragentPaymentOrderOperation {
            get {
                return ResourceManager.GetString("KontragentPaymentOrderOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Займ учредителя.
        /// </summary>
        public static string LoanParentOperation {
            get {
                return ResourceManager.GetString("LoanParentOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Погашение займа учредителю.
        /// </summary>
        public static string LoanParentOutgoingOperation {
            get {
                return ResourceManager.GetString("LoanParentOutgoingOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Займы третьих лиц.
        /// </summary>
        public static string LoansThirdPartiesOperation {
            get {
                return ResourceManager.GetString("LoansThirdPartiesOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Погашение займа третьим лицам.
        /// </summary>
        public static string LoansThirdPartiesOutgoingOperation {
            get {
                return ResourceManager.GetString("LoansThirdPartiesOutgoingOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расходы по виду деятельности.
        /// </summary>
        public static string MainActivityOutgoingOperation {
            get {
                return ResourceManager.GetString("MainActivityOutgoingOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Финансовая помощь.
        /// </summary>
        public static string MaterialAidOperation {
            get {
                return ResourceManager.GetString("MaterialAidOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перевод с кассы на р/сч.
        /// </summary>
        public static string MovementFromCashToSettlementMoneyTransferOperation {
            get {
                return ResourceManager.GetString("MovementFromCashToSettlementMoneyTransferOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перевод электронных денег на р/сч.
        /// </summary>
        public static string MovementFromPurseToSettlementMoneyTransferOperation {
            get {
                return ResourceManager.GetString("MovementFromPurseToSettlementMoneyTransferOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перевод с р/сч на кассу.
        /// </summary>
        public static string MovementFromSettlementToCashMoneyTransferOperation {
            get {
                return ResourceManager.GetString("MovementFromSettlementToCashMoneyTransferOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перевод с р/сч на р/сч.
        /// </summary>
        public static string MovementFromSettlementToSettlementMoneyTransferOperation {
            get {
                return ResourceManager.GetString("MovementFromSettlementToSettlementMoneyTransferOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хозяйственные расходы.
        /// </summary>
        public static string OperatingExpensesOperation {
            get {
                return ResourceManager.GetString("OperatingExpensesOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прочие поступления.
        /// </summary>
        public static string OtherIncomingOperation {
            get {
                return ResourceManager.GetString("OtherIncomingOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прочие расходы.
        /// </summary>
        public static string OtherOutgoingOperation {
            get {
                return ResourceManager.GetString("OtherOutgoingOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выдача зарплаты.
        /// </summary>
        public static string PayDaysOperation {
            get {
                return ResourceManager.GetString("PayDaysOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оказание услуг.
        /// </summary>
        public static string ProvisionOfServicesOperation {
            get {
                return ResourceManager.GetString("ProvisionOfServicesOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Покупка основного средства.
        /// </summary>
        public static string PurchaseOfFixedAssetsOperation {
            get {
                return ResourceManager.GetString("PurchaseOfFixedAssetsOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доход в платежной системе.
        /// </summary>
        public static string PurseIncomingOperation {
            get {
                return ResourceManager.GetString("PurseIncomingOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расход из платежной системы.
        /// </summary>
        public static string PurseOutgoingOperation {
            get {
                return ResourceManager.GetString("PurseOutgoingOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поступление (возврат) из бюджета.
        /// </summary>
        public static string RefundFromBudgetIncomingOperation {
            get {
                return ResourceManager.GetString("RefundFromBudgetIncomingOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возврат от подотчётного лица.
        /// </summary>
        public static string RefundFromEmployeeIncomingOperation {
            get {
                return ResourceManager.GetString("RefundFromEmployeeIncomingOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возврат денег клиенту.
        /// </summary>
        public static string RefundToCustomerOutgoingOperation {
            get {
                return ResourceManager.GetString("RefundToCustomerOutgoingOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Снятие прибыли.
        /// </summary>
        public static string RemovingTheProfitOperation {
            get {
                return ResourceManager.GetString("RemovingTheProfitOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возврат ошибочно переведённых средств.
        /// </summary>
        public static string ReturnFalseMeansIncomingOperation {
            get {
                return ResourceManager.GetString("ReturnFalseMeansIncomingOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возврат от поставщика.
        /// </summary>
        public static string ReturnFromSupplierIncomingOperation {
            get {
                return ResourceManager.GetString("ReturnFromSupplierIncomingOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продажа товара.
        /// </summary>
        public static string SaleProductOperation {
            get {
                return ResourceManager.GetString("SaleProductOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Взнос в УК.
        /// </summary>
        public static string UkInpamentOperation {
            get {
                return ResourceManager.GetString("UkInpamentOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выплата физ.лицу.
        /// </summary>
        public static string WorkerPaymentOperation {
            get {
                return ResourceManager.GetString("WorkerPaymentOperation", resourceCulture);
            }
        }
    }
}
