//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moedelo.AstralV3.Client.BankArchiveService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="tns", ConfigurationName="BankArchiveService.ZipService")]
    public interface ZipService {
        
        // CODEGEN: Контракт генерации сообщений с операцией GetFilesWithUID не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(Action="GetFilesWithUID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(File))]
        Moedelo.AstralV3.Client.BankArchiveService.GetFilesWithUIDResponse1 GetFilesWithUID(Moedelo.AstralV3.Client.BankArchiveService.GetFilesWithUID1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetFilesWithUID", ReplyAction="*")]
        System.Threading.Tasks.Task<Moedelo.AstralV3.Client.BankArchiveService.GetFilesWithUIDResponse1> GetFilesWithUIDAsync(Moedelo.AstralV3.Client.BankArchiveService.GetFilesWithUID1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="tns")]
    public partial class GetFilesWithUID : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string uIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string UID {
            get {
                return this.uIDField;
            }
            set {
                this.uIDField = value;
                this.RaisePropertyChanged("UID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FileWithID))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://iotchet.ru/namespases")]
    public partial class File : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] signaturesField;
        
        private string filenameField;
        
        private byte[] contentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0)]
        public byte[] signatures {
            get {
                return this.signaturesField;
            }
            set {
                this.signaturesField = value;
                this.RaisePropertyChanged("signatures");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string filename {
            get {
                return this.filenameField;
            }
            set {
                this.filenameField = value;
                this.RaisePropertyChanged("filename");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=2)]
        public byte[] content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("content");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://iotchet.ru/namespases")]
    public partial class FileWithID : File {
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=0)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="tns")]
    public partial class GetFilesWithUIDResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FileWithID[] filesWithIDsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="https://iotchet.ru/namespases")]
        public FileWithID[] FilesWithIDs {
            get {
                return this.filesWithIDsField;
            }
            set {
                this.filesWithIDsField = value;
                this.RaisePropertyChanged("FilesWithIDs");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFilesWithUID1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="tns", Order=0)]
        public Moedelo.AstralV3.Client.BankArchiveService.GetFilesWithUID GetFilesWithUID;
        
        public GetFilesWithUID1() {
        }
        
        public GetFilesWithUID1(Moedelo.AstralV3.Client.BankArchiveService.GetFilesWithUID GetFilesWithUID) {
            this.GetFilesWithUID = GetFilesWithUID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFilesWithUIDResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="tns", Order=0)]
        public Moedelo.AstralV3.Client.BankArchiveService.GetFilesWithUIDResponse GetFilesWithUIDResponse;
        
        public GetFilesWithUIDResponse1() {
        }
        
        public GetFilesWithUIDResponse1(Moedelo.AstralV3.Client.BankArchiveService.GetFilesWithUIDResponse GetFilesWithUIDResponse) {
            this.GetFilesWithUIDResponse = GetFilesWithUIDResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ZipServiceChannel : Moedelo.AstralV3.Client.BankArchiveService.ZipService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZipServiceClient : System.ServiceModel.ClientBase<Moedelo.AstralV3.Client.BankArchiveService.ZipService>, Moedelo.AstralV3.Client.BankArchiveService.ZipService {
        
        public ZipServiceClient() {
        }
        
        public ZipServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZipServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZipServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZipServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Moedelo.AstralV3.Client.BankArchiveService.GetFilesWithUIDResponse1 Moedelo.AstralV3.Client.BankArchiveService.ZipService.GetFilesWithUID(Moedelo.AstralV3.Client.BankArchiveService.GetFilesWithUID1 request) {
            return base.Channel.GetFilesWithUID(request);
        }
        
        public Moedelo.AstralV3.Client.BankArchiveService.GetFilesWithUIDResponse GetFilesWithUID(Moedelo.AstralV3.Client.BankArchiveService.GetFilesWithUID GetFilesWithUID1) {
            Moedelo.AstralV3.Client.BankArchiveService.GetFilesWithUID1 inValue = new Moedelo.AstralV3.Client.BankArchiveService.GetFilesWithUID1();
            inValue.GetFilesWithUID = GetFilesWithUID1;
            Moedelo.AstralV3.Client.BankArchiveService.GetFilesWithUIDResponse1 retVal = ((Moedelo.AstralV3.Client.BankArchiveService.ZipService)(this)).GetFilesWithUID(inValue);
            return retVal.GetFilesWithUIDResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Moedelo.AstralV3.Client.BankArchiveService.GetFilesWithUIDResponse1> Moedelo.AstralV3.Client.BankArchiveService.ZipService.GetFilesWithUIDAsync(Moedelo.AstralV3.Client.BankArchiveService.GetFilesWithUID1 request) {
            return base.Channel.GetFilesWithUIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<Moedelo.AstralV3.Client.BankArchiveService.GetFilesWithUIDResponse1> GetFilesWithUIDAsync(Moedelo.AstralV3.Client.BankArchiveService.GetFilesWithUID GetFilesWithUID) {
            Moedelo.AstralV3.Client.BankArchiveService.GetFilesWithUID1 inValue = new Moedelo.AstralV3.Client.BankArchiveService.GetFilesWithUID1();
            inValue.GetFilesWithUID = GetFilesWithUID;
            return ((Moedelo.AstralV3.Client.BankArchiveService.ZipService)(this)).GetFilesWithUIDAsync(inValue);
        }
    }
}
