//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moedelo.Finances.DataAccess.Money.Operations.RefundPaymentAutocomplete {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RefundPaymentAutocompleteQueries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RefundPaymentAutocompleteQueries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Moedelo.Finances.DataAccess.Money.Operations.RefundPaymentAutocomplete.RefundPaym" +
                            "entAutocompleteQueries", typeof(RefundPaymentAutocompleteQueries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --declare @RetailRefundBaseId int, - розн. возврат, из которого был вызван автокомплит
        ///--		@direction int; - направление РКО
        ///
        ///select 
        ///	p.DocumentBaseId,
        ///	p.KontragentId,
        ///	p.Number,
        ///	p.Date,
        ///	p.Sum
        ///from (
        ///	select distinct
        ///		po.DocumentBaseId,
        ///		po.KontragentId,
        ///		po.PaymentNumber Number,
        ///		po.Date,
        ///		po.Sum
        ///	from Accounting_PaymentOrder po
        ///	left join AccountingLinkOfDocuments l on po.DocumentBaseId = l.LinkedFromId and l.Type = @paymentLinkType
        ///	left join AccountingLinkedDocumentBase ldb on [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetByCriterion {
            get {
                return ResourceManager.GetString("GetByCriterion", resourceCulture);
            }
        }
    }
}
