//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moedelo.Finances.DataAccess.Money.Operations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OperationQueries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OperationQueries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Moedelo.Finances.DataAccess.Money.Operations.OperationQueries", typeof(OperationQueries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select po.DocumentBaseId,
        ///		po.Date,
        ///		po.PaymentNumber as Number,
        ///		po.Direction,
        ///		po.KontragentName,
        ///		po.OperationType,
        ///		po.OperationState,
        ///		@PaymentOrderOperationKind as OperationKind,
        ///		po.PaidStatus,
        ///		po.Sum,
        ///		sa.id_currency as Currency,
        ///		po.Description,
        ///		bpo.DocumentBaseId as BaseOperationId
        ///	from dbo.Accounting_PaymentOrder as po
        ///		join dbo.SettlementAccount as sa
        ///			on sa.id = po.SettlementAccountId
        ///		left join dbo.Accounting_PaymentOrder as bpo
        ///			on bpo.id = po.DuplicateId [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetByBaseId {
            get {
                return ResourceManager.GetString("GetByBaseId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string GetByPatent {
            get {
                return ResourceManager.GetString("GetByPatent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select 1
        ///	from dbo.Accounting_PaymentOrder
        ///	where FirmId = @FirmId
        ///		and DocumentBaseId = @DocumentBaseId
        ///union all
        ///select 2
        ///	from dbo.Accounting_CashOrder
        ///	where FirmId = @FirmId
        ///		and DocumentBaseId = @DocumentBaseId
        ///union all
        ///select 3
        ///	from docs.PurseOperation
        ///	where FirmId = @FirmId
        ///		and DocumentBaseId = @DocumentBaseId;.
        /// </summary>
        internal static string GetOperationKind {
            get {
                return ResourceManager.GetString("GetOperationKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select po.DocumentBaseId,
        ///		po.Date,
        ///		po.PaymentNumber as Number,
        ///		po.Direction,
        ///		po.KontragentName,
        ///		po.OperationType,
        ///		po.OperationState,
        ///		@PaymentOrderOperationKind as OperationKind,
        ///		po.PaidStatus,
        ///		po.Sum,
        ///		po.TotalSum,
        ///		sa.id_currency as Currency,
        ///		po.Description,
        ///		bpo.DocumentBaseId as BaseOperationId,
        ///		po.SettlementAccountId as SettlementAccountId,
        ///		po.IsIgnoreNumber,
        ///        po.TaxationSystemType
        ///	from dbo.Accounting_PaymentOrder as po
        ///		join dbo.SettlementAccount as [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetOperations {
            get {
                return ResourceManager.GetString("GetOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select @PaymentOrderOperationKind as OperationKind,
        ///		DocumentBaseId
        ///	from dbo.Accounting_PaymentOrder
        ///	where FirmId = @FirmId
        ///		and DocumentBaseId in (select Id from @BaseIds)
        ///union all
        ///select @CashOrderOperationKind as OperationKind,
        ///		DocumentBaseId
        ///	from dbo.Accounting_CashOrder
        ///	where FirmId = @FirmId
        ///		and DocumentBaseId in (select Id from @BaseIds)
        ///union all
        ///select @PurseOperationOperationKind as OperationKind,
        ///		DocumentBaseId
        ///	from docs.PurseOperation
        ///	where FirmId = @FirmId
        ///		and D [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetOperationsKindsByBaseIds {
            get {
                return ResourceManager.GetString("GetOperationsKindsByBaseIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select @PaymentOrderOperationKind as OperationKind,
        ///		DocumentBaseId
        ///from dbo.Accounting_PaymentOrder
        ///where FirmId = @FirmId
        ///	and id in (select Id from @Ids)
        ///union all
        ///select @CashOrderOperationKind as OperationKind,
        ///	DocumentBaseId
        ///from dbo.Accounting_CashOrder
        ///where FirmId = @FirmId
        ///	and id in (select Id from @Ids)
        ///union all
        ///select @PurseOperationOperationKind as OperationKind,
        ///	DocumentBaseId
        ///from docs.PurseOperation
        ///where FirmId = @FirmId
        ///	and id in (select Id from @Ids)
        ///.
        /// </summary>
        internal static string GetOperationsKindsByIds {
            get {
                return ResourceManager.GetString("GetOperationsKindsByIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select top (@count)
        ///	d.KontragentId,
        ///	sum(d.totalSum) as TotalSum
        ///from (select KontragentId,
        ///				sum(po.Sum) as totalSum
        ///			from dbo.Accounting_PaymentOrder as po
        ///			where FirmId = @firmId
        ///			and po.Date between @startDate and @endDate
        ///			and po.KontragentId is not null
        ///			group by KontragentId
        ///		union all
        ///		select KontragentId,
        ///				sum(co.Sum) as totalSum
        ///			from dbo.Accounting_CashOrder as co
        ///			where FirmId = @firmId
        ///			and co.Date between @startDate and @endDate
        ///			and co.KontragentId is [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TopByOperationsWithKontragentsAcc {
            get {
                return ResourceManager.GetString("TopByOperationsWithKontragentsAcc", resourceCulture);
            }
        }
    }
}
