//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moedelo.Money.PaymentOrders.Business.Tests.Snapshots {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Moedelo.Money.PaymentOrders.Business.Tests.Snapshots.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;PaymentOrder xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;Payer&gt;
        ///    &lt;Name&gt;Гномик&lt;/Name&gt;
        ///    &lt;Inn&gt;5837004553&lt;/Inn&gt;
        ///    &lt;Kpp&gt;111111111&lt;/Kpp&gt;
        ///    &lt;SettlementNumber&gt;12345678912345678912&lt;/SettlementNumber&gt;
        ///    &lt;BankName&gt;ПУ БАНКА РОССИИ N 10462&lt;/BankName&gt;
        ///    &lt;BankBik&gt;040009002&lt;/BankBik&gt;
        ///    &lt;BankCorrespondentAccount /&gt;
        ///    &lt;BankCity /&gt;
        ///    &lt;IsOoo&gt;true&lt;/IsOoo&gt;
        ///    &lt;KontragentType xsi:nil=&quot;true&quot; /&gt;
        ///    &lt;Address /&gt;
        ///    &lt;Okato&gt;45263555000&lt;/Okat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PaymentToSupplier {
            get {
                return ResourceManager.GetString("PaymentToSupplier", resourceCulture);
            }
        }
    }
}
