import SubcontoType from '../../enums/newMoney/SubcontoTypeEnum';

export default {
    [SubcontoType.None]: ``,
    [SubcontoType.Kontragent]: `Контрагент`,
    [SubcontoType.Worker]: `Сотрудник`,
    [SubcontoType.Contract]: `Договоры`,
    [SubcontoType.SettlementAccount]: `Банковские счета`,
    [SubcontoType.Good]: `Номенклатура`,
    [SubcontoType.Stock]: `Склады`,
    [SubcontoType.NdsRate]: `Ставки НДС`,
    [SubcontoType.BudgetaryPayment]: `Виды платежей в бюджет (фонды, КБК)`,
    [SubcontoType.NomenclatureGroup]: `Виды деятельности`,
    [SubcontoType.BasicAsset]: `Основные средства`,
    [SubcontoType.Department]: `Подразделение`,
    [SubcontoType.IntangibleAssets]: `Нематериальные активы`,
    [SubcontoType.FixedAssetInvestment]: `Объекты приобретения, создания строительства`,
    [SubcontoType.CostItems]: `Статья затрат`,
    [SubcontoType.BuildingMethod]: `Способы строительства`,
    [SubcontoType.PerformMethod]: `Способы выполнения`,
    [SubcontoType.TypeOfActives]: `Виды активов и обязательств`,
    [SubcontoType.InvoicesRecieved]: `Первичные документы`,
    [SubcontoType.InvoicesIssued]: `Счета-фактуры выданные`,
    [SubcontoType.MoneyFlow]: `Статьи движения денежных средств`,
    [SubcontoType.Securities]: `Ценные бумаги`,
    [SubcontoType.BudgetaryLevel]: `Уровни бюджетов`,
    [SubcontoType.CalculationWithFss]: `Виды расчетов по средствам ФСС`,
    [SubcontoType.FutureOutgoing]: `Расходы будущих периодов`,
    [SubcontoType.EnforcementDocuments]: `Исполнительные документы`,
    [SubcontoType.SeparateDivision]: `Подразделение`,
    [SubcontoType.UseOfProfit]: `Направления использования прибыли`,
    [SubcontoType.AppointmentOfTrustFunds]: `Назначение целевых средств`,
    [SubcontoType.MovementOfTrustFunds]: `Движения целевых средств`,
    [SubcontoType.OtherIncomeOrOutgo]: `Прочие доходы и расходы`,
    [SubcontoType.EstimatedLiability]: `Оценочные обязательства`,
    [SubcontoType.FutureIncomes]: `Доходы будущих периодов`,
    [SubcontoType.ProfitOrLoss]: `Прибыли и убытки`,
    [SubcontoType.Commissioners]: `Комиссионеры`,
    [SubcontoType.AccountingForms]: `Бланки строгой отчетности`,
    [SubcontoType.ResearchOutgoing]: `Расходы на НИОКР`,
    [SubcontoType.Cashes]: `Кассы`,
    [SubcontoType.Kbk]: `Вид платежа в бюджет`,
    [SubcontoType.Ip]: `Индивидуальный предприниматель`,
    [SubcontoType.UnbalanceFixedAsset]: `Основные средства`,
    [SubcontoType.UnbalanceNomenclature]: `Номенклатура`,
    [SubcontoType.SpecialSettlementAccount]: `Специальные счета`,
    [SubcontoType.Deficit]: `Номенклатура, ОС и др.`,
    [SubcontoType.UnbalanceStock]: `Склады`,
    [SubcontoType.MiddlemanContract]: `Посреднический договор`,
    [SubcontoType.SpecialSettlementAccountForDigitalRuble]: `Специальные счета`
};
