//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moedelo.Finances.DataAccess.Money.Balances {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BalancesQueries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BalancesQueries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Moedelo.Finances.DataAccess.Money.Balances.BalancesQueries", typeof(BalancesQueries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select @MoneySourceTypeCash as Type,
        ///		CashId as Id,
        ///		isnull(sum(iif(Direction = @IncomingDirection, Sum, -Sum)), 0) as Balance
        ///	from dbo.Accounting_CashOrder
        ///	where FirmId = @FirmId
        ///		and Date between @BalancesMasterDate and @OnDate
        ///		/* SourceFilter */
        ///	group by CashId
        ///.
        /// </summary>
        internal static string GetCashOrderBalances {
            get {
                return ResourceManager.GetString("GetCashOrderBalances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select @MoneySourceTypeSettlementAccount as Type,
        ///	SettlementAccountId as Id,
        ///	isnull(sum(iif(Direction = @IncomingDirection, Sum, -Sum)), 0) as Balance
        ///	from dbo.Accounting_PaymentOrder
        ///	where FirmId = @FirmId
        ///		and PaidStatus = @PayedDocumentStatus
        ///		and Date between @BalancesMasterDate and @OnDate
        ///		and isnull(OperationState, @DefaultOperationState) not in (select Id from @BadOperationStates)
        ///		/* SourceFilter */
        ///	group by SettlementAccountId
        ///.
        /// </summary>
        internal static string GetPaymentOrderBalances {
            get {
                return ResourceManager.GetString("GetPaymentOrderBalances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select @MoneySourceTypePurse as Type,
        ///		PurseId as Id,
        ///		isnull(sum(iif(Direction = @IncomingDirection, Sum, -Sum)), 0) as Balance
        ///	from docs.PurseOperation as po
        ///	where FirmId = @FirmId
        ///		and po.[DocumentDate] between @BalancesMasterDate and @OnDate
        ///		/* SourceFilter */
        ///	group by PurseId
        ///.
        /// </summary>
        internal static string GetPurseOperationBalances {
            get {
                return ResourceManager.GetString("GetPurseOperationBalances", resourceCulture);
            }
        }
    }
}
