//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moedelo.Finances.DataAccess.ClosedPeriods {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Sql {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sql() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Moedelo.Finances.DataAccess.ClosedPeriods.Sql", typeof(Sql).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select top 1 EndDate
        ///	from dbo.ClosedPeriod
        ///	where FirmId = @FirmId
        ///	order by EndDate desc;.
        /// </summary>
        internal static string GetLastClosedDate {
            get {
                return ResourceManager.GetString("GetLastClosedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select count(*) as Count,
        ///		p.Direction as Direction,
        ///		@paymentOrderType as Type,
        ///		p.OrderType as DocumentType
        ///	from dbo.Accounting_PaymentOrder as p
        ///	where p.FirmId = @FirmId
        ///		and p.ProvideInAccounting = 0
        ///		and p.Date between @StartDate and @EndDate
        ///	group by p.Direction,
        ///		p.OrderType
        ///
        ///union all
        ///select count(*) as Count,
        ///		c.Direction as Direction,
        ///		case c.Direction
        ///			when 2 then @incomingCashOrder
        ///			else @outcomingCashOrder
        ///		end as Type,
        ///		@emptyDocumentType as DocumentType
        ///	from [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetNonProvidedInAccountingOrderCounts {
            get {
                return ResourceManager.GetString("GetNonProvidedInAccountingOrderCounts", resourceCulture);
            }
        }
    }
}
