const DocumentTypeEnum = {
    Default: 0,
    Waybill: 1,
    Invoice: 2,
    StockDocument: 3,
    AccountingStatement: 4,
    PaymentOrder: 5,
    Statement: 6,
    ReturnFromBuyer: 7,
    IncomingStatementOfFixedAsset: 8,
    IncomingCashOrder: 9,
    OutcomingCashOrder: 10,
    AccountingAdvanceStatement: 11,
    RetailReport: 12,
    Bill: 13,
    Contract: 14,
    FixedAssetClosedPeriod: 15,
    Salary: 16,
    ReturnToSupplier: 17,
    InventoryCard: 18,
    FixedAssetInvestment: 19,
    FinancialOperation: 21,
    MiddlemanContract: 24,
    MiddlemanReport: 25,
    PurseOperation: 31,
    Upd: 33,
    SalesUpd: 36,
    ReceiptStatement: 54,
    SalesCurrencyInvoice: 55,
    PurchasesCurrencyInvoice: 56,
    Ukd: 57,
    PaymentReserve: 60,
    Other: 101
};

export default DocumentTypeEnum;
