//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moedelo.BankIntegrations.Converter1C.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PredicatesResourceNew {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PredicatesResourceNew() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Moedelo.BankIntegrations.Converter1C.Resources.PredicatesResourceNew", typeof(PredicatesResourceNew).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to агент.
        /// </summary>
        internal static string Agent {
            get {
                return ResourceManager.GetString("Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to КонечныйОстаток.
        /// </summary>
        internal static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Банковский ордер.
        /// </summary>
        internal static string BankWarrant {
            get {
                return ResourceManager.GetString("BankWarrant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПоказательДаты.
        /// </summary>
        internal static string BudgetaryDocDate {
            get {
                return ResourceManager.GetString("BudgetaryDocDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПоказательНомера.
        /// </summary>
        internal static string BudgetaryDocNumber {
            get {
                return ResourceManager.GetString("BudgetaryDocNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to СтатусСоставителя.
        /// </summary>
        internal static string BudgetaryPayerStatus {
            get {
                return ResourceManager.GetString("BudgetaryPayerStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПоказательОснования.
        /// </summary>
        internal static string BudgetaryPaymentBase {
            get {
                return ResourceManager.GetString("BudgetaryPaymentBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПоказательТипа.
        /// </summary>
        internal static string BudgetaryPaymentType {
            get {
                return ResourceManager.GetString("BudgetaryPaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to объявление на взнос наличными.
        /// </summary>
        internal static string CashPayment {
            get {
                return ResourceManager.GetString("CashPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код.
        /// </summary>
        internal static string CodeUin {
            get {
                return ResourceManager.GetString("CodeUin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to комиссия.
        /// </summary>
        internal static string Comission {
            get {
                return ResourceManager.GetString("Comission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to комис..
        /// </summary>
        internal static string Comission2 {
            get {
                return ResourceManager.GetString("Comission2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to дивиденд.
        /// </summary>
        internal static string DividendPayment {
            get {
                return ResourceManager.GetString("DividendPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        internal static string DocDate {
            get {
                return ResourceManager.GetString("DocDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер.
        /// </summary>
        internal static string DocumentNumber {
            get {
                return ResourceManager.GetString("DocumentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to взнос в ук.
        /// </summary>
        internal static string DonationToCharterCapital {
            get {
                return ResourceManager.GetString("DonationToCharterCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ДатаКонца.
        /// </summary>
        internal static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to КонецДокумента.
        /// </summary>
        internal static string EndDocumentSection {
            get {
                return ResourceManager.GetString("EndDocumentSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ДатаПоступило.
        /// </summary>
        internal static string IncomingDate {
            get {
                return ResourceManager.GetString("IncomingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПоказательКБК.
        /// </summary>
        internal static string IndicatorKbk {
            get {
                return ResourceManager.GetString("IndicatorKbk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to взнос на счет ип.
        /// </summary>
        internal static string InpaymentToIpAccount {
            get {
                return ResourceManager.GetString("InpaymentToIpAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to займ учредителя.
        /// </summary>
        internal static string LoanParent1 {
            get {
                return ResourceManager.GetString("LoanParent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to займ от учредителя.
        /// </summary>
        internal static string LoanParent2 {
            get {
                return ResourceManager.GetString("LoanParent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to б/п займ.
        /// </summary>
        internal static string LoanParent3 {
            get {
                return ResourceManager.GetString("LoanParent3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to беспроцентный займ.
        /// </summary>
        internal static string LoanParent4 {
            get {
                return ResourceManager.GetString("LoanParent4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to без % займ.
        /// </summary>
        internal static string LoanParent5 {
            get {
                return ResourceManager.GetString("LoanParent5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to б/п  займ.
        /// </summary>
        internal static string LoanParent6 {
            get {
                return ResourceManager.GetString("LoanParent6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to договору бе спроцентного займа.
        /// </summary>
        internal static string LoanParent7 {
            get {
                return ResourceManager.GetString("LoanParent7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мемориальный ордер.
        /// </summary>
        internal static string MemorialWarrant {
            get {
                return ResourceManager.GetString("MemorialWarrant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объявление на взнос наличными.
        /// </summary>
        internal static string MemorialWarrantIncomingFromCash {
            get {
                return ResourceManager.GetString("MemorialWarrantIncomingFromCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Денежный чек.
        /// </summary>
        internal static string MoneyOrder {
            get {
                return ResourceManager.GetString("MoneyOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объявление на взнос наличными.
        /// </summary>
        internal static string MovementFromCashToSettlement {
            get {
                return ResourceManager.GetString("MovementFromCashToSettlement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Денежный чек.
        /// </summary>
        internal static string MovementFromSettlementToCash {
            get {
                return ResourceManager.GetString("MovementFromSettlementToCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Платежное поручение.
        /// </summary>
        internal static string MovementFromSettlementToSettlement {
            get {
                return ResourceManager.GetString("MovementFromSettlementToSettlement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ОКАТО.
        /// </summary>
        internal static string Okato {
            get {
                return ResourceManager.GetString("Okato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ДатаСписано.
        /// </summary>
        internal static string OutgoingDate {
            get {
                return ResourceManager.GetString("OutgoingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to собствен.
        /// </summary>
        internal static string Own {
            get {
                return ResourceManager.GetString("Own", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Плательщик.
        /// </summary>
        internal static string Payer {
            get {
                return ResourceManager.GetString("Payer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Плательщик1.
        /// </summary>
        internal static string Payer1 {
            get {
                return ResourceManager.GetString("Payer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПлательщикСчет.
        /// </summary>
        internal static string PayerAccount {
            get {
                return ResourceManager.GetString("PayerAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПлательщикБанк1.
        /// </summary>
        internal static string PayerBankName {
            get {
                return ResourceManager.GetString("PayerBankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПлательщикБИК.
        /// </summary>
        internal static string PayerBik {
            get {
                return ResourceManager.GetString("PayerBik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПлательщикКорсчет.
        /// </summary>
        internal static string PayerCorrespondentAccount {
            get {
                return ResourceManager.GetString("PayerCorrespondentAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПлательщикИНН.
        /// </summary>
        internal static string PayerInn {
            get {
                return ResourceManager.GetString("PayerInn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПлательщикКПП.
        /// </summary>
        internal static string PayerKpp {
            get {
                return ResourceManager.GetString("PayerKpp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ВидОплаты.
        /// </summary>
        internal static string PaymentKind {
            get {
                return ResourceManager.GetString("PaymentKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очередность.
        /// </summary>
        internal static string PaymentPriority {
            get {
                return ResourceManager.GetString("PaymentPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to НазначениеПлатежа.
        /// </summary>
        internal static string PaymentPurpose {
            get {
                return ResourceManager.GetString("PaymentPurpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to КодНазПлатежа.
        /// </summary>
        internal static string PaymentPurposeCode {
            get {
                return ResourceManager.GetString("PaymentPurposeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очередность.
        /// </summary>
        internal static string PaymentTurn {
            get {
                return ResourceManager.GetString("PaymentTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПоказательПериода.
        /// </summary>
        internal static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получатель.
        /// </summary>
        internal static string Recipient {
            get {
                return ResourceManager.GetString("Recipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получатель1.
        /// </summary>
        internal static string Recipient1 {
            get {
                return ResourceManager.GetString("Recipient1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПолучательСчет.
        /// </summary>
        internal static string RecipientAccount {
            get {
                return ResourceManager.GetString("RecipientAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПолучательБанк1.
        /// </summary>
        internal static string RecipientBankName {
            get {
                return ResourceManager.GetString("RecipientBankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПолучательБИК.
        /// </summary>
        internal static string RecipientBik {
            get {
                return ResourceManager.GetString("RecipientBik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПолучательКорсчет.
        /// </summary>
        internal static string RecipientCorrespondentAccount {
            get {
                return ResourceManager.GetString("RecipientCorrespondentAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПолучательИНН.
        /// </summary>
        internal static string RecipientInn {
            get {
                return ResourceManager.GetString("RecipientInn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПолучательКПП.
        /// </summary>
        internal static string RecipientKpp {
            get {
                return ResourceManager.GetString("RecipientKpp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to снятие прибыли.
        /// </summary>
        internal static string removingTheProfit {
            get {
                return ResourceManager.GetString("removingTheProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to пополнение личного счета.
        /// </summary>
        internal static string removingTheProfit10 {
            get {
                return ResourceManager.GetString("removingTheProfit10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to собственных средств.
        /// </summary>
        internal static string removingTheProfit2 {
            get {
                return ResourceManager.GetString("removingTheProfit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to перевод личных средств на карту.
        /// </summary>
        internal static string removingTheProfit3 {
            get {
                return ResourceManager.GetString("removingTheProfit3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to получение личных средств.
        /// </summary>
        internal static string removingTheProfit4 {
            get {
                return ResourceManager.GetString("removingTheProfit4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to перечисление дохода от предпринимательской деятельности.
        /// </summary>
        internal static string removingTheProfit5 {
            get {
                return ResourceManager.GetString("removingTheProfit5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to вывод личных средств.
        /// </summary>
        internal static string removingTheProfit6 {
            get {
                return ResourceManager.GetString("removingTheProfit6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to перевод денежных средств от предпринимательской деятельности.
        /// </summary>
        internal static string removingTheProfit7 {
            get {
                return ResourceManager.GetString("removingTheProfit7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to пополнение личного счёта.
        /// </summary>
        internal static string removingTheProfit8 {
            get {
                return ResourceManager.GetString("removingTheProfit8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to собственные средства.
        /// </summary>
        internal static string removingTheProfit9 {
            get {
                return ResourceManager.GetString("removingTheProfit9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to на счета работников.
        /// </summary>
        internal static string SalaryProjectPayment1 {
            get {
                return ResourceManager.GetString("SalaryProjectPayment1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to на счета сотрудников.
        /// </summary>
        internal static string SalaryProjectPayment2 {
            get {
                return ResourceManager.GetString("SalaryProjectPayment2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to реестр.
        /// </summary>
        internal static string SalaryProjectPayment3 {
            get {
                return ResourceManager.GetString("SalaryProjectPayment3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to СекцияДокумент.
        /// </summary>
        internal static string SectionName {
            get {
                return ResourceManager.GetString("SectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to услуг.
        /// </summary>
        internal static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to РасчСчет.
        /// </summary>
        internal static string Settlement {
            get {
                return ResourceManager.GetString("Settlement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to НачальныйОстаток.
        /// </summary>
        internal static string StartBalance {
            get {
                return ResourceManager.GetString("StartBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ДатаНачала.
        /// </summary>
        internal static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to СекцияДокумент.
        /// </summary>
        internal static string StartDocumentSection {
            get {
                return ResourceManager.GetString("StartDocumentSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сумма.
        /// </summary>
        internal static string Sum {
            get {
                return ResourceManager.GetString("Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неизвестный.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to зарплат.
        /// </summary>
        internal static string WorkerPay1 {
            get {
                return ResourceManager.GetString("WorkerPay1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to заработн.
        /// </summary>
        internal static string WorkerPay2 {
            get {
                return ResourceManager.GetString("WorkerPay2", resourceCulture);
            }
        }
    }
}
