//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moedelo.Finances.DataAccess.Money.Reconcilation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ReconcilationQueries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReconcilationQueries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Moedelo.Finances.DataAccess.Money.Reconcilation.ReconcilationQueries", typeof(ReconcilationQueries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select top 1
        ///	Id,
        ///	SettlementAccountId,
        ///	ServiceBalance,
        ///	BankBalance,
        ///	ReconcilationDate,
        ///	CreateDate,
        ///	SessionId,
        ///	Status
        ///	from dbo.BalanceReconcilation
        ///	where FirmId = @FirmId
        ///		and Status = @ReadyStatus
        ///	order by id;
        ///.
        /// </summary>
        internal static string Get {
            get {
                return ResourceManager.GetString("Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select top 1
        ///	Id,
        ///	SettlementAccountId,
        ///	ServiceBalance,
        ///	BankBalance,
        ///	ReconcilationDate,
        ///	CreateDate,
        ///	SessionId,
        ///	Status
        ///	from dbo.BalanceReconcilation
        ///	where FirmId = @FirmId
        ///	    /*--FilterBySettlementAccountId--and SettlementAccountId = @SettlementAccountId--FilterBySettlementAccountId--*/
        ///	order by Id desc;
        ///.
        /// </summary>
        internal static string GetByDate {
            get {
                return ResourceManager.GetString("GetByDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select Id,
        ///	ServiceBalance,
        ///	BankBalance,
        ///	ReconcilationDate,
        ///	CreateDate,
        ///	SessionId,
        ///	Status,
        ///	SettlementAccountId
        ///	from dbo.BalanceReconcilation 
        ///	where FirmId = @FirmId
        ///	and SessionId = @SessionId;
        ///.
        /// </summary>
        internal static string GetBySessionId {
            get {
                return ResourceManager.GetString("GetBySessionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select top 1
        ///	Id,
        ///	SettlementAccountId,
        ///	ServiceBalance,
        ///	BankBalance,
        ///	ReconcilationDate,
        ///	CreateDate,
        ///	SessionId,
        ///	Status
        ///	from dbo.BalanceReconcilation
        ///	where FirmId = @FirmId
        ///	    /*--FilterBySettlementAccountId--and SettlementAccountId = @SettlementAccountId--FilterBySettlementAccountId--*/
        ///	order by Id desc;
        ///.
        /// </summary>
        internal static string GetLast {
            get {
                return ResourceManager.GetString("GetLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        ///declare @FirmId int = 4359699;
        ///declare @Status int = 3;
        ///*/
        ///
        ///;with OrderedSettlementAccountIds as (
        ///	select 
        ///		Id,
        ///		SettlementAccountId,
        ///		ServiceBalance,
        ///		BankBalance,
        ///		ReconcilationDate,
        ///		CreateDate,
        ///		SessionId,
        ///		Status,
        ///	    row_number() over(partition by SettlementAccountId order by Id desc) as RowNumber
        ///	from BalanceReconcilation 
        ///		--inner join #SettlementAccountIds sa on sa.id = BalanceReconcilation.SettlementAccountId
        ///	where FirmId = @FirmId 
        ///	and Status = @Status
        ///	and Se [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetLastBySettlementAccountIds {
            get {
                return ResourceManager.GetString("GetLastBySettlementAccountIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select top 1
        ///	Id,
        ///	SettlementAccountId,
        ///	ServiceBalance,
        ///	BankBalance,
        ///	ReconcilationDate,
        ///	CreateDate,
        ///	SessionId,
        ///	Status
        ///	from dbo.BalanceReconcilation
        ///	where FirmId = @FirmId and SettlementAccountId = @SettlementAccountId
        ///	order by Id desc;
        ///.
        /// </summary>
        internal static string GetLastForSettlementAccount {
            get {
                return ResourceManager.GetString("GetLastForSettlementAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select top 1
        ///	SessionId
        ///	from dbo.BalanceReconcilation
        ///	where FirmId = @FirmId
        ///		and SettlementAccountId = @SettlementAccountId
        ///		and Status = @InProgressStatus
        ///		and CreateDate &gt; @DayAgo
        ///	order by id desc;
        ///.
        /// </summary>
        internal static string GetLastSessionIdInProcess {
            get {
                return ResourceManager.GetString("GetLastSessionIdInProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select
        ///	max(CreateDate)
        ///	from dbo.BalanceReconcilation
        ///	where FirmId = @firmId
        ///		and SettlementAccountId = @settlementAccountId;.
        /// </summary>
        internal static string GetMaxCreateDate {
            get {
                return ResourceManager.GetString("GetMaxCreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select distinct(SettlementAccountId)
        ///from dbo.BalanceReconcilation
        ///where FirmId = @FirmId
        ///	and Status = @InProgressStatus
        ///	and CreateDate &gt;= @ActualDays
        ///	and SettlementAccountId in (select Id from @SettlementAccountIds);.
        /// </summary>
        internal static string GetSettlementAccountsInProgress {
            get {
                return ResourceManager.GetString("GetSettlementAccountsInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into dbo.BalanceReconcilation
        ///	(FirmId, ServiceBalance, BankBalance, ReconcilationDate, CreateDate, SessionId, Status, SettlementAccountId)
        ///values
        ///	(@FirmId,
        ///	@ServiceBalance,
        ///	@BankBalance,
        ///	@ReconcilationDate,
        ///	@CreateDate,
        ///	@SessionId,
        ///	@Status,
        ///	@SettlementAccountId);
        ///.
        /// </summary>
        internal static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if (exists
        ///	(select
        ///		1
        ///		from dbo.BalanceReconcilation
        ///		where FirmId = @firmId
        ///			and SettlementAccountId = @settlementAccountId
        ///			and Status = @inProgressStatus))
        ///	select 1;
        ///else select 0;.
        /// </summary>
        internal static string IsAnyInProgress {
            get {
                return ResourceManager.GetString("IsAnyInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update
        ///	dbo.BalanceReconcilation
        ///	set
        ///	Status = @completeStatus
        ///	where FirmId = @FirmId
        ///		and Status = @readyStatus
        ///		and SettlementAccountId = @settlementAccountId;.
        /// </summary>
        internal static string SetReadyToComplete {
            get {
                return ResourceManager.GetString("SetReadyToComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update
        ///	dbo.BalanceReconcilation
        ///	set
        ///	Status = @status
        ///	where FirmId = @firmId
        ///		and SessionId = @sessionId;.
        /// </summary>
        internal static string SetStatus {
            get {
                return ResourceManager.GetString("SetStatus", resourceCulture);
            }
        }
    }
}
