//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moedelo.Finances.DataAccess.Money.Operations.PaymentOrders {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PaymentOrdersDuplicatesQueries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PaymentOrdersDuplicatesQueries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Moedelo.Finances.DataAccess.Money.Operations.PaymentOrders.PaymentOrdersDuplicate" +
                            "sQueries", typeof(PaymentOrdersDuplicatesQueries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select
        ///	po.Id,
        ///	po.DocumentBaseId,
        ///	po.Direction,
        ///	po.Description,
        ///	po.SettlementAccountId,
        ///	po.KontragentId,
        ///	po.PaymentNumber																							as Number,
        ///	isnull(po.PaymentSnapshot.value(&apos;(/PaymentOrder/Payer/SettlementNumber/node())[1]&apos;, &apos;varchar(20)&apos;), &apos;&apos;)		as PayerSettlementNumber,
        ///	isnull(po.PaymentSnapshot.value(&apos;(/PaymentOrder/Payer/Inn/node())[1]&apos;, &apos;varchar(12)&apos;), &apos;&apos;)					as PayerInn,
        ///	isnull(po.PaymentSnapshot.value(&apos;(/PaymentOrder/Recipient/SettlementNumber/node())[1]&apos;, &apos;varchar(20 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetAllPaymentOrders {
            get {
                return ResourceManager.GetString("GetAllPaymentOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select
        ///	po.Id,
        ///	po.DocumentBaseId,
        ///	po.Sum,
        ///	po.Description,
        ///	po.KontragentId,
        ///	po.PaymentNumber																							as Number,
        ///	isnull(po.PaymentSnapshot.value(&apos;(/PaymentOrder/Payer/SettlementNumber/node())[1]&apos;, &apos;varchar(20)&apos;), &apos;&apos;)		as PayerSettlementNumber,
        ///	isnull(po.PaymentSnapshot.value(&apos;(/PaymentOrder/Payer/Inn/node())[1]&apos;, &apos;varchar(12)&apos;), &apos;&apos;)					as PayerInn,
        ///	isnull(po.PaymentSnapshot.value(&apos;(/PaymentOrder/Recipient/SettlementNumber/node())[1]&apos;, &apos;varchar(20)&apos;), &apos;&apos;) as RecipientSettlementN [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetForBatchDetection {
            get {
                return ResourceManager.GetString("GetForBatchDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select po.Id
        ///	from dbo.Accounting_PaymentOrder as po
        ///	where po.FirmId = @FirmId
        ///		and po.PaymentNumber = @PaymentOrderNumber
        ///		and po.Sum = @Sum
        ///		and po.Direction = @Direction
        ///		and po.Date between @StartDate and @EndDate
        ///		and isnull(po.OperationState, @RegularOperationState) not in (select Id from @BadOperationStates)
        ///	order by iif(po.Date = @Date, 0, 1),
        ///		po.Id desc;.
        /// </summary>
        internal static string GetPaymentOrderId {
            get {
                return ResourceManager.GetString("GetPaymentOrderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set nocount on;
        ///set transaction isolation level read uncommitted;
        ///
        ///declare @id int = null
        ///declare @baseId bigint = null
        ///
        ///select @id = po.Id, @baseId = po.DocumentBaseId
        ///	from dbo.Accounting_PaymentOrder as po
        ///	where po.FirmId = @FirmId
        ///		and po.PaymentNumber = iif(@Direction = 1, po.PaymentNumber, @PaymentOrderNumber)
        ///		and po.Sum = @Sum
        ///		and po.Direction = @Direction
        ///		and po.Date = @Date
        ///		and (@SettlementAccountId is null or po.SettlementAccountId = @SettlementAccountId)
        ///		and po.Descripti [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetPaymentOrderIdExt {
            get {
                return ResourceManager.GetString("GetPaymentOrderIdExt", resourceCulture);
            }
        }
    }
}
