//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moedelo.Finances.DataAccess.Money.Operations.PaymentOrders {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PaymentOrderOperationQueries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PaymentOrderOperationQueries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Moedelo.Finances.DataAccess.Money.Operations.PaymentOrders.PaymentOrderOperationQ" +
                            "ueries", typeof(PaymentOrderOperationQueries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select
        ///--TopConstraint-- top(@TopConstraint)
        ///po.Id,
        ///po.FirmId,
        ///po.DocumentBaseId,
        ///po.Date,
        ///po.PaymentNumber as Number,
        ///po.Direction,
        ///po.SettlementAccountId,
        ///po.KontragentSettlementAccountId as TransferSettlementAccountId,
        ///po.KontragentId,
        ///po.KontragentName,
        ///po.SalaryWorkerId as WorkerId,
        ///po.OperationType,
        ///po.OrderType,
        ///po.OperationState,
        ///po.PaidStatus,
        ///po.Sum,
        ///po.Description,
        ///po.PaymentPriority,
        ///po.PaymentSnapshot,
        ///po.IncludeNds,
        ///po.NdsSum,
        ///po.NdsType,
        ///po.UnderContract,
        ///po.SourceFileId,
        ///po.KbkId,
        ///--SelectKb [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Get {
            get {
                return ResourceManager.GetString("Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select DocumentBaseId
        ///	from dbo.Accounting_PaymentOrder
        ///	where FirmId = @FirmId
        ///		and isnull(OperationState, @RegularOperationState) in (select Id from @UnrecognizedOperationStates)
        ///		and isnull(po.OutsourceState, 0) &lt;&gt; @UnconfirmedOutsourceState
        ///		and (coalesce(@sourceId, 0) = 0 or SettlementAccountId = @sourceId);
        ///.
        /// </summary>
        internal static string GetBaseIdsForUncategorized {
            get {
                return ResourceManager.GetString("GetBaseIdsForUncategorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select po2.DocumentBaseId
        ///	from dbo.Accounting_PaymentOrder as po
        ///		join @BaseIds as baseIds
        ///			on baseIds.Id = po.DocumentBaseId
        ///		join dbo.Accounting_PaymentOrder as po2
        ///			on po2.DuplicateId = po.Id
        ///	where po.FirmId = @FirmId and po2.FirmId = @FirmId;.
        /// </summary>
        internal static string GetDuplicateBaseIdsByOriginalBaseIds {
            get {
                return ResourceManager.GetString("GetDuplicateBaseIdsByOriginalBaseIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select max(dates.Date)
        ///	from (select max(Date) as Date
        ///				from dbo.Accounting_PaymentOrder
        ///				where FirmId = @FirmId
        ///					and Date &lt;= @Date
        ///			union all
        ///			select max(Date) as Date
        ///				from dbo.Accounting_CashOrder
        ///				where FirmId = @FirmId
        ///					and Date &lt;= @Date
        ///			union all
        ///			select max(DocumentDate) as Date
        ///				from docs.PurseOperation
        ///				where FirmId = @FirmId
        ///					and DocumentDate &lt;= @Date) as dates;
        ///.
        /// </summary>
        internal static string GetLastDateUntil {
            get {
                return ResourceManager.GetString("GetLastDateUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select	po.DocumentBaseId,
        ///		po.PaidStatus as DocumentStatus
        ///	from dbo.Accounting_PaymentOrder as po
        ///		join @BaseIds as ids
        ///			on ids.Id = po.DocumentBaseId
        ///	where po.FirmId = @FirmId;
        ///.
        /// </summary>
        internal static string GetStatusesByBaseIds {
            get {
                return ResourceManager.GetString("GetStatusesByBaseIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select 
        ///--TopConstraint-- top(@TopConstraint)
        ///	po.Id,
        ///	po.FirmId,
        ///	po.DocumentBaseId,
        ///	po.Date,
        ///	po.PaymentNumber as Number,
        ///	po.Direction,
        ///	po.SettlementAccountId,
        ///	po.KontragentSettlementAccountId as TransferSettlementAccountId,
        ///	po.KontragentId,
        ///	po.KontragentName,
        ///	po.SalaryWorkerId as WorkerId,
        ///	po.OperationType,
        ///	po.OrderType,
        ///	po.OperationState,
        ///	po.PaidStatus,
        ///	po.Sum,
        ///	po.Description,
        ///	po.PaymentPriority,
        ///	po.PaymentSnapshot,
        ///	po.IncludeNds,
        ///	po.NdsSum,
        ///	po.NdsType,
        ///	po.UnderContract,
        ///	po.SourceFil [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetWithUnifiedTaxPayments {
            get {
                return ResourceManager.GetString("GetWithUnifiedTaxPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if exists (select 1
        ///			from dbo.Accounting_PaymentOrder
        ///			where FirmId = @FirmId
        ///				and SettlementAccountId = @SettlementAccountId)
        ///	select 1;
        ///else
        ///	select 0;
        ///.
        /// </summary>
        internal static string HasOperationsBySettlementAccount {
            get {
                return ResourceManager.GetString("HasOperationsBySettlementAccount", resourceCulture);
            }
        }
    }
}
