set nocount on;

update
	dbo.Accounting_PaymentOrder
	set
	Date = @Date,
	PaymentNumber = @Number,
	Sum = @Sum,
	SettlementAccountId = @SettlementAccountId,
	KontragentAccountCode = @KontragentAccountCode,
	IsMediation = @IsMediation,
	MediationCommission = @MediationCommission,
	AcquiringCommission = @AcquiringCommission,
	AcquiringCommissionDate = @AcquiringCommissionDate,
	NdsType = @NdsType,
	NdsSum = @NdsSum,
	IncludeNds = @IncludeNds,
	Description = @Description,
	KontragentId = @KontragentId,
	KontragentName = @KontragentName,
	PaymentSnapshot = @PaymentSnapshot,
	OperationState = @OperationState,
	ProvideInAccounting = @ProvideInAccounting,
	TaxPostingType = @TaxPostingType,
	OperationType = @OperationType,
	OrderType = @OrderType,
	TaxationSystemType = @TaxationSystemType,
	PaidStatus = @PaidStatus,
	IsLongTermLoan = @IsLongTermLoan,
	UnderContract = @UnderContract,
	BudgetaryTaxesAndFees = @BudgetaryTaxesAndFees,
	BudgetaryPeriodType = @BudgetaryPeriodType,
	BudgetaryPeriodNumber = @BudgetaryPeriodNumber,
	BudgetaryPeriodYear = @BudgetaryPeriodYear,
	BudgetaryPeriodDate = @BudgetaryPeriodDate,
	KbkPaymentType = @KbkPaymentType,
	KbkId = @KbkId,
	PaymentPriority = @PaymentPriority,
	ExchangeRate = @exchangeRate,
	TotalSum = @totalSum,
	ExchangeRateDiff = @exchangeRateDiff,
	KontragentSettlementAccountId = @TransferSettlementAccountId,
	SalaryWorkerId = @SalaryWorkerId,
	TradingObjectId = @TradingObjectId,
	LoanInterestSum = @LoanInterestSum,
	PatentId = @PatentId,
	DuplicateId = @DuplicateId,
	SaleDate = @SaleDate,
	IsTargetIncome = @IsTargetIncome,
	OutsourceState = @OutsourceState,
	MediationNdsType = @MediationNdsType,
	MediationNdsSum = @MediationNdsSum,
	ModifyDate = @ModifyDate
where DocumentBaseId = @DocumentBaseId
	and FirmId = @FirmId;
