//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moedelo.Parsers.Klto1CParser.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Predicates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Predicates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Moedelo.Parsers.Klto1CParser.Resources.Predicates", typeof(Predicates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1CClientBankExchange.
        /// </summary>
        internal static string _1CClientBankExchange {
            get {
                return ResourceManager.GetString("_1CClientBankExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ВсегоПоступило.
        /// </summary>
        internal static string AllIncome {
            get {
                return ResourceManager.GetString("AllIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ВсегоСписано.
        /// </summary>
        internal static string AllOutgo {
            get {
                return ResourceManager.GetString("AllOutgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 17.
        /// </summary>
        internal static string BankOrderPaymentKind {
            get {
                return ResourceManager.GetString("BankOrderPaymentKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Банковский ордер.
        /// </summary>
        internal static string BankWarrant {
            get {
                return ResourceManager.GetString("BankWarrant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ДатаНачала.
        /// </summary>
        internal static string BeginDate {
            get {
                return ResourceManager.GetString("BeginDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПоказательДаты.
        /// </summary>
        internal static string BudgetaryDocDate {
            get {
                return ResourceManager.GetString("BudgetaryDocDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПоказательНомера.
        /// </summary>
        internal static string BudgetaryDocNumber {
            get {
                return ResourceManager.GetString("BudgetaryDocNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to СтатусСоставителя.
        /// </summary>
        internal static string BudgetaryPayerStatus {
            get {
                return ResourceManager.GetString("BudgetaryPayerStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПоказательОснования.
        /// </summary>
        internal static string BudgetaryPaymentBase {
            get {
                return ResourceManager.GetString("BudgetaryPaymentBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПоказательТипа.
        /// </summary>
        internal static string BudgetaryPaymentType {
            get {
                return ResourceManager.GetString("BudgetaryPaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to объявление на взнос наличными.
        /// </summary>
        internal static string CashPayment {
            get {
                return ResourceManager.GetString("CashPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код.
        /// </summary>
        internal static string CodeUin {
            get {
                return ResourceManager.GetString("CodeUin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ДатаСоздания.
        /// </summary>
        internal static string CreationDate {
            get {
                return ResourceManager.GetString("CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ВремяСоздания.
        /// </summary>
        internal static string CreationTime {
            get {
                return ResourceManager.GetString("CreationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        internal static string DocDate {
            get {
                return ResourceManager.GetString("DocDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Документ.
        /// </summary>
        internal static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер.
        /// </summary>
        internal static string DocumentNumber {
            get {
                return ResourceManager.GetString("DocumentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to СекцияДокумент.
        /// </summary>
        internal static string DocumentSection {
            get {
                return ResourceManager.GetString("DocumentSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кодировка.
        /// </summary>
        internal static string Encoding {
            get {
                return ResourceManager.GetString("Encoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to КонечныйОстаток.
        /// </summary>
        internal static string EndBalance {
            get {
                return ResourceManager.GetString("EndBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ДатаКонца.
        /// </summary>
        internal static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to КонецДокумента.
        /// </summary>
        internal static string EndDocumentSection {
            get {
                return ResourceManager.GetString("EndDocumentSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to КонецФайла.
        /// </summary>
        internal static string EndOfFile {
            get {
                return ResourceManager.GetString("EndOfFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to КонецРасчСчет.
        /// </summary>
        internal static string EndOfSettlementSection {
            get {
                return ResourceManager.GetString("EndOfSettlementSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ВерсияФормата.
        /// </summary>
        internal static string FormatVersion {
            get {
                return ResourceManager.GetString("FormatVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ДатаПоступило.
        /// </summary>
        internal static string IncomingDate {
            get {
                return ResourceManager.GetString("IncomingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПоказательКБК.
        /// </summary>
        internal static string IndicatorKbk {
            get {
                return ResourceManager.GetString("IndicatorKbk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мемориальный ордер.
        /// </summary>
        internal static string MemorialWarrant {
            get {
                return ResourceManager.GetString("MemorialWarrant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объявление на взнос наличными.
        /// </summary>
        internal static string MemorialWarrantIncomingFromCash {
            get {
                return ResourceManager.GetString("MemorialWarrantIncomingFromCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to moedelo.org.
        /// </summary>
        internal static string MoedeloOrg {
            get {
                return ResourceManager.GetString("MoedeloOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Денежный чек.
        /// </summary>
        internal static string MoneyOrder {
            get {
                return ResourceManager.GetString("MoneyOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ОКАТО.
        /// </summary>
        internal static string Okato {
            get {
                return ResourceManager.GetString("Okato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ДатаСписано.
        /// </summary>
        internal static string OutgoingDate {
            get {
                return ResourceManager.GetString("OutgoingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to собствен.
        /// </summary>
        internal static string Own {
            get {
                return ResourceManager.GetString("Own", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Плательщик.
        /// </summary>
        internal static string Payer {
            get {
                return ResourceManager.GetString("Payer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Плательщик1.
        /// </summary>
        internal static string Payer1 {
            get {
                return ResourceManager.GetString("Payer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПлательщикСчет.
        /// </summary>
        internal static string PayerAccount {
            get {
                return ResourceManager.GetString("PayerAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПлательщикБанк.
        /// </summary>
        internal static string PayerBankName {
            get {
                return ResourceManager.GetString("PayerBankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПлательщикБанк1.
        /// </summary>
        internal static string PayerBankName1 {
            get {
                return ResourceManager.GetString("PayerBankName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПлательщикБИК.
        /// </summary>
        internal static string PayerBik {
            get {
                return ResourceManager.GetString("PayerBik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПлательщикКорсчет.
        /// </summary>
        internal static string PayerCorrespondentAccount {
            get {
                return ResourceManager.GetString("PayerCorrespondentAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПлательщикИНН.
        /// </summary>
        internal static string PayerInn {
            get {
                return ResourceManager.GetString("PayerInn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПлательщикКПП.
        /// </summary>
        internal static string PayerKpp {
            get {
                return ResourceManager.GetString("PayerKpp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПлательщикРасчСчет.
        /// </summary>
        internal static string PayerSettlementAccount {
            get {
                return ResourceManager.GetString("PayerSettlementAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ВидОплаты.
        /// </summary>
        internal static string PaymentKind {
            get {
                return ResourceManager.GetString("PaymentKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очередность.
        /// </summary>
        internal static string PaymentPriority {
            get {
                return ResourceManager.GetString("PaymentPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to НазначениеПлатежа.
        /// </summary>
        internal static string PaymentPurpose {
            get {
                return ResourceManager.GetString("PaymentPurpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to НазначениеПлатежа1.
        /// </summary>
        internal static string PaymentPurpose1 {
            get {
                return ResourceManager.GetString("PaymentPurpose1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очередность.
        /// </summary>
        internal static string PaymentTurn {
            get {
                return ResourceManager.GetString("PaymentTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ВидПлатежа.
        /// </summary>
        internal static string PaymentType {
            get {
                return ResourceManager.GetString("PaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to процент.
        /// </summary>
        internal static string Percent {
            get {
                return ResourceManager.GetString("Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПоказательПериода.
        /// </summary>
        internal static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получатель.
        /// </summary>
        internal static string Recipient {
            get {
                return ResourceManager.GetString("Recipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получатель1.
        /// </summary>
        internal static string Recipient1 {
            get {
                return ResourceManager.GetString("Recipient1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПолучательСчет.
        /// </summary>
        internal static string RecipientAccount {
            get {
                return ResourceManager.GetString("RecipientAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПолучательБанк.
        /// </summary>
        internal static string RecipientBankName {
            get {
                return ResourceManager.GetString("RecipientBankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПолучательБанк1.
        /// </summary>
        internal static string RecipientBankName1 {
            get {
                return ResourceManager.GetString("RecipientBankName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПолучательБИК.
        /// </summary>
        internal static string RecipientBik {
            get {
                return ResourceManager.GetString("RecipientBik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПолучательКорсчет.
        /// </summary>
        internal static string RecipientCorrespondentAccount {
            get {
                return ResourceManager.GetString("RecipientCorrespondentAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПолучательИНН.
        /// </summary>
        internal static string RecipientInn {
            get {
                return ResourceManager.GetString("RecipientInn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПолучательКПП.
        /// </summary>
        internal static string RecipientKpp {
            get {
                return ResourceManager.GetString("RecipientKpp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПолучательРасчСчет.
        /// </summary>
        internal static string RecipientSettlementAccount {
            get {
                return ResourceManager.GetString("RecipientSettlementAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправитель.
        /// </summary>
        internal static string Sender {
            get {
                return ResourceManager.GetString("Sender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to РасчСчет.
        /// </summary>
        internal static string Settlement {
            get {
                return ResourceManager.GetString("Settlement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to СекцияРасчСчет.
        /// </summary>
        internal static string SettlementSection {
            get {
                return ResourceManager.GetString("SettlementSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to НачальныйОстаток.
        /// </summary>
        internal static string StartBalance {
            get {
                return ResourceManager.GetString("StartBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ДатаНачала.
        /// </summary>
        internal static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сумма.
        /// </summary>
        internal static string Sum {
            get {
                return ResourceManager.GetString("Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неизвестный.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.02.
        /// </summary>
        internal static string Version102 {
            get {
                return ResourceManager.GetString("Version102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows.
        /// </summary>
        internal static string Windows {
            get {
                return ResourceManager.GetString("Windows", resourceCulture);
            }
        }
    }
}
