//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moedelo.AstralV3.Client.DAO.SQL {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlScripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlScripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Moedelo.AstralV3.Client.DAO.SQL.SqlScripts", typeof(SqlScripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into moedelo_logs.dbo.AstralInteractionLog
        ///(
        ///	MethodId,
        ///	FirmId,
        ///	UserId,
        ///	EventDateTime,
        ///	EventType,
        ///	ExceptionMessage,
        ///	Request,
        ///	Response,
        ///	Duration
        ///)
        ///values
        ///(
        ///	@MethodId,
        ///	@FirmId,
        ///	@UserId,
        ///	@EventDateTime,
        ///	@EventType,
        ///	@ExceptionMessage,
        ///	@Request,
        ///	@Response,
        ///	@Duration
        ///);.
        /// </summary>
        internal static string AstralLogger_AddInteractionLog {
            get {
                return ResourceManager.GetString("AstralLogger_AddInteractionLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into moedelo_logs.dbo.AstralInteractionMethod
        ///(
        ///	MethodName,
        ///	Mode
        ///)
        ///values
        ///(
        ///	@methodName,
        ///	@mode
        ///)
        ///SELECT SCOPE_IDENTITY()
        ///.
        /// </summary>
        internal static string AstralLogger_AddInteractionMethod {
            get {
                return ResourceManager.GetString("AstralLogger_AddInteractionMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select
        ///	Id				as Id,
        ///	MethodName		as MethodName,
        ///	Mode			as Mode
        ///from
        ///    moedelo_logs.dbo.AstralInteractionMethod
        ///where
        ///    Id in @ids.
        /// </summary>
        internal static string AstralLogger_GetInteractionMethodsByIds {
            get {
                return ResourceManager.GetString("AstralLogger_GetInteractionMethodsByIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select
        ///	Id				as Id,
        ///	MethodName		as MethodName,
        ///	Mode			as Mode
        ///from
        ///    moedelo_logs.dbo.AstralInteractionMethod
        ///where
        ///    MethodName in @methodNames
        ///.
        /// </summary>
        internal static string AstralLogger_GetInteractionMethodsByNames {
            get {
                return ResourceManager.GetString("AstralLogger_GetInteractionMethodsByNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete
        ///from
        ///	dbo.AstralInteractionLog
        ///where
        ///	EventDateTime &lt; @thresholdDate.
        /// </summary>
        internal static string AstralLogger_RemoveInteractionLogs {
            get {
                return ResourceManager.GetString("AstralLogger_RemoveInteractionLogs", resourceCulture);
            }
        }
    }
}
