//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moedelo.Finances.DataAccess.FinancialOperations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Sql {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sql() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Moedelo.Finances.DataAccess.FinancialOperations.Sql", typeof(Sql).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select
        ///	fo.id,
        ///	fo.DocumentBaseId,
        ///	mtot.type																								as Direction,
        ///	mto.destanition_description																				as Description,
        ///	mto.SettlementAccountId,
        ///	mto.kontragent_id																						as KontragentId,
        ///	mto.number_of_document																					as Number,
        ///	mto.settlement_account																					as PayerSettlementNumber,
        ///	&apos;&apos;																										as PayerInn,
        ///	coalesce(ksa.Number, mto.RecipientSettlement)															as RecipientSettlementNumber,
        ///	coalesce(k.i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetAllIncomingOperations {
            get {
                return ResourceManager.GetString("GetAllIncomingOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select
        ///	fo.id,
        ///	fo.DocumentBaseId,
        ///	mtot.type																								as Direction,
        ///	mto.destanition_description																				as Description,
        ///	mto.SettlementAccountId,
        ///	mto.kontragent_id																						as KontragentId,
        ///	mto.number_of_document																					as Number,
        ///	mto.settlement_account																					as PayerSettlementNumber,
        ///	&apos;&apos;																										as PayerInn,
        ///	coalesce(ksa.Number, mto.RecipientSettlement)															as RecipientSettlementNumber,
        ///	coalesce(k.i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetAllOutgoingOperations {
            get {
                return ResourceManager.GetString("GetAllOutgoingOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select fo.id as Id
        ///from dbo.FinancialOperation as fo
        ///    inner join dbo.MoneyTransferOperation as mto
        ///        on mto.id = fo.id
        ///    inner join dbo.MoneyTransferOperationType as mtot
        ///        on fo.type = mtot.name
        ///where fo.firm_id = @FirmId
        ///      and fo.type = @BudgetaryPaymentOperationType
        ///      and fo.operation_date
        ///      between @StartDate and @EndDate
        ///      and mto.summ = @Sum
        ///      and mto.budgetary_payment_type = @BudgetaryPaymentType
        ///      and
        ///      (
        ///          @BudgetaryPaymentSubtype i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetBudgetaryPaymentOperationDuplicateId {
            get {
                return ResourceManager.GetString("GetBudgetaryPaymentOperationDuplicateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select fo.id as Id
        ///	from dbo.FinancialOperation as fo
        ///		inner join dbo.MoneyTransferOperation as mto
        ///			on mto.id = fo.id
        ///		inner join dbo.MoneyTransferOperationType as mtot
        ///			on fo.type = mtot.name
        ///	where fo.firm_id = @FirmId
        ///		and fo.type = @DividendPaymentOperationType
        ///		and mto.PaymentType = @PayDaysPaymentDividendType
        ///		and fo.operation_date between @StartDate and @EndDate
        ///		and mto.summ = @Sum
        ///		and isnull(mto.number_of_document, &apos;&apos;) = isnull(@PaymentOrderNumber, &apos;&apos;)
        ///		and mto.SettlementA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetDividendPaymentOperationDuplicateId {
            get {
                return ResourceManager.GetString("GetDividendPaymentOperationDuplicateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select
        ///	fo.id,
        ///	fo.DocumentBaseId,
        ///	case 
        ///		when mtot.type = @IncomingDirection
        ///				or mtot.name in (&apos;MovementFromCashToSettlementMoneyTransferOperation&apos;,
        ///								&apos;MovementFromPurseToSettlementMoneyTransferOperation&apos;,
        ///								&apos;MovementFromSettlementToSettlementMoneyTransferOperation&apos;)) then 1
        ///		when mtot.type = @OutgoingDirection
        ///				or mtot.name = &apos;MovementFromSettlementToCashMoneyTransferOperation&apos;)
        ///			or mto.MovementSettlementAccountId = @SettlementAccountId
        ///			and mtot.name in (&apos;MovementFromS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetForBatchDetection {
            get {
                return ResourceManager.GetString("GetForBatchDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select fo.id
        ///	from dbo.FinancialOperation as fo
        ///		inner join dbo.MoneyTransferOperation as mto
        ///			on mto.id = fo.id
        ///		inner join dbo.MoneyTransferOperationType as mtot
        ///			on fo.type = mtot.name
        ///	where fo.firm_id = @FirmId
        ///		and fo.type = &apos;MaterialAidOperation&apos;
        ///		and fo.operation_date between @StartDate and @EndDate
        ///		and mto.summ = @Sum
        ///		and mto.SettlementAccountId = @SettlementAccountId
        ///		and mto.kontragent_id = @KontragentId
        ///	order by fo.id desc;
        ///.
        /// </summary>
        internal static string GetMaterialAidOperationDuplicateId {
            get {
                return ResourceManager.GetString("GetMaterialAidOperationDuplicateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select fo.id
        ///	from dbo.FinancialOperation as fo
        ///		inner join dbo.MoneyTransferOperation as mto
        ///			on mto.id = fo.id
        ///		inner join dbo.MoneyTransferOperationType as mtot
        ///			on fo.type = mtot.name
        ///	where fo.firm_id = @FirmId
        ///		and mtot.type = @Direction
        ///		and fo.type != @CurrencyBalanceOperationType
        ///		and fo.operation_date between @StartDate and @EndDate
        ///		and mto.summ = @Sum
        ///		and isnull(mto.number_of_document, &apos;&apos;) = isnull(@PaymentOrderNumber, &apos;&apos;)
        ///		and (mto.SettlementAccountId = @MovementSettlem [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetMovementOperationDuplicateId {
            get {
                return ResourceManager.GetString("GetMovementOperationDuplicateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select fo.id
        ///	from dbo.FinancialOperation as fo
        ///		inner join dbo.MoneyTransferOperation as mto
        ///			on mto.id = fo.id
        ///		inner join dbo.MoneyTransferOperationType as mtot
        ///			on fo.type = mtot.name
        ///		left outer join dbo.Kontragent as k
        ///			on mto.kontragent_id = k.id
        ///		left outer join dbo.KontragentSettlementAccount as ksa
        ///			on mto.KontragentSettlementAccountId = ksa.Id
        ///		left outer join dbo.Salary_WorkerCardAccount as swca
        ///			on mto.worker_id = swca.worker_id
        ///	where fo.firm_id = @FirmId
        ///		and mtot [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetOperationDuplicateId {
            get {
                return ResourceManager.GetString("GetOperationDuplicateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select fo.id
        ///	from dbo.FinancialOperation as fo
        ///		inner join dbo.MoneyTransferOperation as mto
        ///			on mto.id = fo.id
        ///		inner join dbo.MoneyTransferOperationType as mtot
        ///			on fo.type = mtot.name
        ///	where fo.firm_id = @FirmId
        ///		and mtot.type = @Direction
        ///		and fo.type != @CurrencyBalanceOperationType
        ///		and fo.operation_date = convert(date, @Date)
        ///		and (mto.summ = @Sum or mto.summ_for_usn = @Sum)
        ///		and mto.destanition_description = @DestinationDescription
        ///	order by fo.id desc;
        ///.
        /// </summary>
        internal static string GetRoboAndSapeIncomingOperationDuplicateId {
            get {
                return ResourceManager.GetString("GetRoboAndSapeIncomingOperationDuplicateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select fo.id
        ///	from dbo.FinancialOperation as fo
        ///		inner join dbo.MoneyTransferOperation as mto
        ///			on mto.id = fo.id
        ///		inner join dbo.MoneyTransferOperationType as mtot
        ///			on fo.type = mtot.name
        ///	where fo.firm_id = @FirmId
        ///		and mtot.type = @Direction
        ///		and fo.type != @CurrencyBalanceOperationType
        ///		and fo.operation_date = convert(date, @Date)
        ///		and mto.summ = @Sum
        ///		and mto.destanition_description = @DestinationDescription
        ///	order by fo.id desc;
        ///.
        /// </summary>
        internal static string GetRoboAndSapeOutgoingOperationDuplicateId {
            get {
                return ResourceManager.GetString("GetRoboAndSapeOutgoingOperationDuplicateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select fo.id
        ///	from dbo.FinancialOperation as fo
        ///		inner join dbo.MoneyTransferOperation as mto
        ///			on mto.id = fo.id
        ///		inner join dbo.MoneyTransferOperationType as mtot
        ///			on fo.type = mtot.name
        ///	where fo.firm_id = @FirmId
        ///		and fo.type = &apos;UkInpamentOperation&apos;
        ///		and fo.operation_date between @StartDate and @EndDate
        ///		and mto.summ = @Sum
        ///		and mto.SettlementAccountId = @SettlementAccountId
        ///		and mto.kontragent_id = @KontragentId
        ///	order by fo.id desc;
        ///.
        /// </summary>
        internal static string GetUkInpamentOperationDuplicateId {
            get {
                return ResourceManager.GetString("GetUkInpamentOperationDuplicateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select fo.id as Id
        ///	from dbo.FinancialOperation as fo
        ///		inner join dbo.MoneyTransferOperation as mto
        ///			on mto.id = fo.id
        ///		inner join dbo.MoneyTransferOperationType as mtot
        ///			on fo.type = mtot.name
        ///	where fo.firm_id = @FirmId
        ///		and mtot.type = @Direction
        ///		and fo.type != @CurrencyBalanceOperationType
        ///		and fo.operation_date = convert(date, @Date)
        ///		and mto.summ = @Sum
        ///		and mto.number_of_document = @PaymentOrderNumber
        ///	order by fo.id;
        ///.
        /// </summary>
        internal static string GetYandexMovementOperationDuplicateId {
            get {
                return ResourceManager.GetString("GetYandexMovementOperationDuplicateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select fo.id as Id
        ///	from dbo.FinancialOperation as fo
        ///		inner join dbo.MoneyTransferOperation as mto
        ///			on mto.id = fo.id
        ///		inner join dbo.MoneyTransferOperationType as mtot
        ///			on fo.type = mtot.name
        ///	where fo.firm_id = @FirmId
        ///		and mtot.type = @Direction
        ///		and fo.type != @CurrencyBalanceOperationType
        ///		and fo.operation_date = convert(date, @Date)
        ///		and mto.summ = @Sum
        ///		and mto.destanition_description = @DestinationDescription
        ///		and mto.kontragent_id = @KontragentId
        ///	order by fo.id;
        ///.
        /// </summary>
        internal static string GetYandexOperationDuplicateId {
            get {
                return ResourceManager.GetString("GetYandexOperationDuplicateId", resourceCulture);
            }
        }
    }
}
