using System;

namespace Moedelo.Common.Enums.Enums.Header
{
    [Obsolete("This enum moved into https://github.com/moedelo/md-header/blob/master/src/api/header/enums/Moedelo.Header.Enums/MenuItemType.cs")]
    public enum MenuItemType
    {
        Nothing = 0,
        Accounting = 1,
        Analytics = 2,
        Bank = 3,
        Bills = 4,
        BizStock = 5,
        Buy = 6,
        CashForUsn = 7,
        Cash = 8,
        Egr = 9,
        EReport = 10,
        Estate = 11,
        Kontragents = 12,
        Legal = 13,
        MainForUsnAccountant = 14,
        Main = 15,
        Money = 16,
        PayrollAnalytic = 17,
        Payroll = 18,
        PayrollPayments = 19,
        PayrollReport = 20,
        Personal = 21,
        Pro = 22,
        Projects = 23,
        ProQa = 24,
        ProSales = 25,
        ProWebinars = 26,
        Registry = 27,
        Sales = 28,
        Statements = 30,
        Stock = 31,
        Tools = 32,
        MainForOffice = 33,
        OfficeForms = 34,
        OfficeDepartmentalInspection = 35,
        OfficeCalculators = 36,
        OfficeCheckKontragent = 37,
        MainForBillsAndDocuments = 38,
        BillsAndDocuments = 39,
        OutsourceCompanies = 40,
        OutsourceUsers = 41,
        OutsourceJoin = 42,
        OutsourceAdmin = 43,
        OfficeMainForBiz = 44,
        OfficeMainForUsn = 45,
        AnalyticsAccountantChamber = 46,
        Movement = 47,
        MyBonuses = 169
    }
}
