//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moedelo.AstralV3.Client.AstralAuthServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="tns", ConfigurationName="AstralAuthServiceReference.AutorizationService")]
    public interface AutorizationService {
        
        // CODEGEN: Generating message contract since the operation GetPassword is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="GetPassword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Moedelo.AstralV3.Client.AstralAuthServiceReference.GetPasswordResponse1 GetPassword(Moedelo.AstralV3.Client.AstralAuthServiceReference.GetPassword1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetPassword", ReplyAction="*")]
        System.Threading.Tasks.Task<Moedelo.AstralV3.Client.AstralAuthServiceReference.GetPasswordResponse1> GetPasswordAsync(Moedelo.AstralV3.Client.AstralAuthServiceReference.GetPassword1 request);
        
        // CODEGEN: Generating message contract since the operation GetSessionkeyByCert is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="GetSessionkeyByCert", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Moedelo.AstralV3.Client.AstralAuthServiceReference.GetSessionkeyByCertResponse1 GetSessionkeyByCert(Moedelo.AstralV3.Client.AstralAuthServiceReference.GetSessionkeyByCert1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetSessionkeyByCert", ReplyAction="*")]
        System.Threading.Tasks.Task<Moedelo.AstralV3.Client.AstralAuthServiceReference.GetSessionkeyByCertResponse1> GetSessionkeyByCertAsync(Moedelo.AstralV3.Client.AstralAuthServiceReference.GetSessionkeyByCert1 request);
        
        // CODEGEN: Generating message contract since the operation GetEncryptedSessionkey is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="GetEncryptedSessionkey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Moedelo.AstralV3.Client.AstralAuthServiceReference.GetEncryptedSessionkeyResponse1 GetEncryptedSessionkey(Moedelo.AstralV3.Client.AstralAuthServiceReference.GetEncryptedSessionkey1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetEncryptedSessionkey", ReplyAction="*")]
        System.Threading.Tasks.Task<Moedelo.AstralV3.Client.AstralAuthServiceReference.GetEncryptedSessionkeyResponse1> GetEncryptedSessionkeyAsync(Moedelo.AstralV3.Client.AstralAuthServiceReference.GetEncryptedSessionkey1 request);
        
        // CODEGEN: Generating message contract since the operation GetPasswordBySkid is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="GetPasswordBySkid", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Moedelo.AstralV3.Client.AstralAuthServiceReference.GetPasswordBySkidResponse1 GetPasswordBySkid(Moedelo.AstralV3.Client.AstralAuthServiceReference.GetPasswordBySkid1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetPasswordBySkid", ReplyAction="*")]
        System.Threading.Tasks.Task<Moedelo.AstralV3.Client.AstralAuthServiceReference.GetPasswordBySkidResponse1> GetPasswordBySkidAsync(Moedelo.AstralV3.Client.AstralAuthServiceReference.GetPasswordBySkid1 request);
        
        // CODEGEN: Generating message contract since the operation GetSessionkeyBySMS is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="GetSessionkeyBySMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Moedelo.AstralV3.Client.AstralAuthServiceReference.GetSessionkeyBySMSResponse1 GetSessionkeyBySMS(Moedelo.AstralV3.Client.AstralAuthServiceReference.GetSessionkeyBySMS1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetSessionkeyBySMS", ReplyAction="*")]
        System.Threading.Tasks.Task<Moedelo.AstralV3.Client.AstralAuthServiceReference.GetSessionkeyBySMSResponse1> GetSessionkeyBySMSAsync(Moedelo.AstralV3.Client.AstralAuthServiceReference.GetSessionkeyBySMS1 request);
        
        // CODEGEN: Generating message contract since the operation DropSessionKey is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="DropSessionKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Moedelo.AstralV3.Client.AstralAuthServiceReference.DropSessionKeyResponse1 DropSessionKey(Moedelo.AstralV3.Client.AstralAuthServiceReference.DropSessionKey1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="DropSessionKey", ReplyAction="*")]
        System.Threading.Tasks.Task<Moedelo.AstralV3.Client.AstralAuthServiceReference.DropSessionKeyResponse1> DropSessionKeyAsync(Moedelo.AstralV3.Client.AstralAuthServiceReference.DropSessionKey1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="tns")]
    public partial class AutorizationHeaderWithExtra : RequestHeader {
        
        private string extraField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string extra {
            get {
                return this.extraField;
            }
            set {
                this.extraField = value;
                this.RaisePropertyChanged("extra");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AutorizationHeaderWithExtra))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="tns")]
    public partial class RequestHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sysnameField;
        
        private string sessionkeyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string sysname {
            get {
                return this.sysnameField;
            }
            set {
                this.sysnameField = value;
                this.RaisePropertyChanged("sysname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string sessionkey {
            get {
                return this.sessionkeyField;
            }
            set {
                this.sessionkeyField = value;
                this.RaisePropertyChanged("sessionkey");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="tns")]
    public partial class DropSessionKeyResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="tns")]
    public partial class DropSessionKey : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sessionkeyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Sessionkey {
            get {
                return this.sessionkeyField;
            }
            set {
                this.sessionkeyField = value;
                this.RaisePropertyChanged("Sessionkey");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="tns")]
    public partial class GetSessionkeyBySMSResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sessionkeyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Sessionkey {
            get {
                return this.sessionkeyField;
            }
            set {
                this.sessionkeyField = value;
                this.RaisePropertyChanged("Sessionkey");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="tns")]
    public partial class GetSessionkeyBySMS : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string gUIDField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string GUID {
            get {
                return this.gUIDField;
            }
            set {
                this.gUIDField = value;
                this.RaisePropertyChanged("GUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="tns")]
    public partial class GetPasswordBySkidResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="tns")]
    public partial class GetPasswordBySkid : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string gUIDField;
        
        private string sKIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string GUID {
            get {
                return this.gUIDField;
            }
            set {
                this.gUIDField = value;
                this.RaisePropertyChanged("GUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string SKID {
            get {
                return this.sKIDField;
            }
            set {
                this.sKIDField = value;
                this.RaisePropertyChanged("SKID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="tns")]
    public partial class GetEncryptedSessionkeyResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] sessionkeyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0)]
        public byte[] Sessionkey {
            get {
                return this.sessionkeyField;
            }
            set {
                this.sessionkeyField = value;
                this.RaisePropertyChanged("Sessionkey");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="tns")]
    public partial class GetEncryptedSessionkey : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string gUIDField;
        
        private string sKIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string GUID {
            get {
                return this.gUIDField;
            }
            set {
                this.gUIDField = value;
                this.RaisePropertyChanged("GUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string SKID {
            get {
                return this.sKIDField;
            }
            set {
                this.sKIDField = value;
                this.RaisePropertyChanged("SKID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="tns")]
    public partial class GetSessionkeyByCertResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sessionkeyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Sessionkey {
            get {
                return this.sessionkeyField;
            }
            set {
                this.sessionkeyField = value;
                this.RaisePropertyChanged("Sessionkey");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="tns")]
    public partial class GetSessionkeyByCert : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dataField;
        
        private byte[] signatureField;
        
        private string gUIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("Data");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] Signature {
            get {
                return this.signatureField;
            }
            set {
                this.signatureField = value;
                this.RaisePropertyChanged("Signature");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string GUID {
            get {
                return this.gUIDField;
            }
            set {
                this.gUIDField = value;
                this.RaisePropertyChanged("GUID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="tns")]
    public partial class GetPasswordResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="tns")]
    public partial class GetPassword : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string gUIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string GUID {
            get {
                return this.gUIDField;
            }
            set {
                this.gUIDField = value;
                this.RaisePropertyChanged("GUID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPassword1 {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="tns")]
        public Moedelo.AstralV3.Client.AstralAuthServiceReference.AutorizationHeaderWithExtra AutorizationHeaderWithExtra;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="tns", Order=0)]
        public Moedelo.AstralV3.Client.AstralAuthServiceReference.GetPassword GetPassword;
        
        public GetPassword1() {
        }
        
        public GetPassword1(Moedelo.AstralV3.Client.AstralAuthServiceReference.AutorizationHeaderWithExtra AutorizationHeaderWithExtra, Moedelo.AstralV3.Client.AstralAuthServiceReference.GetPassword GetPassword) {
            this.AutorizationHeaderWithExtra = AutorizationHeaderWithExtra;
            this.GetPassword = GetPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPasswordResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="tns", Order=0)]
        public Moedelo.AstralV3.Client.AstralAuthServiceReference.GetPasswordResponse GetPasswordResponse;
        
        public GetPasswordResponse1() {
        }
        
        public GetPasswordResponse1(Moedelo.AstralV3.Client.AstralAuthServiceReference.GetPasswordResponse GetPasswordResponse) {
            this.GetPasswordResponse = GetPasswordResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSessionkeyByCert1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="tns", Order=0)]
        public Moedelo.AstralV3.Client.AstralAuthServiceReference.GetSessionkeyByCert GetSessionkeyByCert;
        
        public GetSessionkeyByCert1() {
        }
        
        public GetSessionkeyByCert1(Moedelo.AstralV3.Client.AstralAuthServiceReference.GetSessionkeyByCert GetSessionkeyByCert) {
            this.GetSessionkeyByCert = GetSessionkeyByCert;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSessionkeyByCertResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="tns", Order=0)]
        public Moedelo.AstralV3.Client.AstralAuthServiceReference.GetSessionkeyByCertResponse GetSessionkeyByCertResponse;
        
        public GetSessionkeyByCertResponse1() {
        }
        
        public GetSessionkeyByCertResponse1(Moedelo.AstralV3.Client.AstralAuthServiceReference.GetSessionkeyByCertResponse GetSessionkeyByCertResponse) {
            this.GetSessionkeyByCertResponse = GetSessionkeyByCertResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEncryptedSessionkey1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="tns", Order=0)]
        public Moedelo.AstralV3.Client.AstralAuthServiceReference.GetEncryptedSessionkey GetEncryptedSessionkey;
        
        public GetEncryptedSessionkey1() {
        }
        
        public GetEncryptedSessionkey1(Moedelo.AstralV3.Client.AstralAuthServiceReference.GetEncryptedSessionkey GetEncryptedSessionkey) {
            this.GetEncryptedSessionkey = GetEncryptedSessionkey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEncryptedSessionkeyResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="tns", Order=0)]
        public Moedelo.AstralV3.Client.AstralAuthServiceReference.GetEncryptedSessionkeyResponse GetEncryptedSessionkeyResponse;
        
        public GetEncryptedSessionkeyResponse1() {
        }
        
        public GetEncryptedSessionkeyResponse1(Moedelo.AstralV3.Client.AstralAuthServiceReference.GetEncryptedSessionkeyResponse GetEncryptedSessionkeyResponse) {
            this.GetEncryptedSessionkeyResponse = GetEncryptedSessionkeyResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPasswordBySkid1 {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="tns")]
        public Moedelo.AstralV3.Client.AstralAuthServiceReference.AutorizationHeaderWithExtra AutorizationHeaderWithExtra;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="tns", Order=0)]
        public Moedelo.AstralV3.Client.AstralAuthServiceReference.GetPasswordBySkid GetPasswordBySkid;
        
        public GetPasswordBySkid1() {
        }
        
        public GetPasswordBySkid1(Moedelo.AstralV3.Client.AstralAuthServiceReference.AutorizationHeaderWithExtra AutorizationHeaderWithExtra, Moedelo.AstralV3.Client.AstralAuthServiceReference.GetPasswordBySkid GetPasswordBySkid) {
            this.AutorizationHeaderWithExtra = AutorizationHeaderWithExtra;
            this.GetPasswordBySkid = GetPasswordBySkid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPasswordBySkidResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="tns", Order=0)]
        public Moedelo.AstralV3.Client.AstralAuthServiceReference.GetPasswordBySkidResponse GetPasswordBySkidResponse;
        
        public GetPasswordBySkidResponse1() {
        }
        
        public GetPasswordBySkidResponse1(Moedelo.AstralV3.Client.AstralAuthServiceReference.GetPasswordBySkidResponse GetPasswordBySkidResponse) {
            this.GetPasswordBySkidResponse = GetPasswordBySkidResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSessionkeyBySMS1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="tns", Order=0)]
        public Moedelo.AstralV3.Client.AstralAuthServiceReference.GetSessionkeyBySMS GetSessionkeyBySMS;
        
        public GetSessionkeyBySMS1() {
        }
        
        public GetSessionkeyBySMS1(Moedelo.AstralV3.Client.AstralAuthServiceReference.GetSessionkeyBySMS GetSessionkeyBySMS) {
            this.GetSessionkeyBySMS = GetSessionkeyBySMS;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSessionkeyBySMSResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="tns", Order=0)]
        public Moedelo.AstralV3.Client.AstralAuthServiceReference.GetSessionkeyBySMSResponse GetSessionkeyBySMSResponse;
        
        public GetSessionkeyBySMSResponse1() {
        }
        
        public GetSessionkeyBySMSResponse1(Moedelo.AstralV3.Client.AstralAuthServiceReference.GetSessionkeyBySMSResponse GetSessionkeyBySMSResponse) {
            this.GetSessionkeyBySMSResponse = GetSessionkeyBySMSResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DropSessionKey1 {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="tns")]
        public Moedelo.AstralV3.Client.AstralAuthServiceReference.RequestHeader RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="tns", Order=0)]
        public Moedelo.AstralV3.Client.AstralAuthServiceReference.DropSessionKey DropSessionKey;
        
        public DropSessionKey1() {
        }
        
        public DropSessionKey1(Moedelo.AstralV3.Client.AstralAuthServiceReference.RequestHeader RequestHeader, Moedelo.AstralV3.Client.AstralAuthServiceReference.DropSessionKey DropSessionKey) {
            this.RequestHeader = RequestHeader;
            this.DropSessionKey = DropSessionKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DropSessionKeyResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="tns", Order=0)]
        public Moedelo.AstralV3.Client.AstralAuthServiceReference.DropSessionKeyResponse DropSessionKeyResponse;
        
        public DropSessionKeyResponse1() {
        }
        
        public DropSessionKeyResponse1(Moedelo.AstralV3.Client.AstralAuthServiceReference.DropSessionKeyResponse DropSessionKeyResponse) {
            this.DropSessionKeyResponse = DropSessionKeyResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AutorizationServiceChannel : Moedelo.AstralV3.Client.AstralAuthServiceReference.AutorizationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AutorizationServiceClient : System.ServiceModel.ClientBase<Moedelo.AstralV3.Client.AstralAuthServiceReference.AutorizationService>, Moedelo.AstralV3.Client.AstralAuthServiceReference.AutorizationService {
        
        public AutorizationServiceClient() {
        }
        
        public AutorizationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AutorizationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AutorizationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AutorizationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Moedelo.AstralV3.Client.AstralAuthServiceReference.GetPasswordResponse1 Moedelo.AstralV3.Client.AstralAuthServiceReference.AutorizationService.GetPassword(Moedelo.AstralV3.Client.AstralAuthServiceReference.GetPassword1 request) {
            return base.Channel.GetPassword(request);
        }
        
        public Moedelo.AstralV3.Client.AstralAuthServiceReference.GetPasswordResponse GetPassword(Moedelo.AstralV3.Client.AstralAuthServiceReference.AutorizationHeaderWithExtra AutorizationHeaderWithExtra, Moedelo.AstralV3.Client.AstralAuthServiceReference.GetPassword GetPassword1) {
            Moedelo.AstralV3.Client.AstralAuthServiceReference.GetPassword1 inValue = new Moedelo.AstralV3.Client.AstralAuthServiceReference.GetPassword1();
            inValue.AutorizationHeaderWithExtra = AutorizationHeaderWithExtra;
            inValue.GetPassword = GetPassword1;
            Moedelo.AstralV3.Client.AstralAuthServiceReference.GetPasswordResponse1 retVal = ((Moedelo.AstralV3.Client.AstralAuthServiceReference.AutorizationService)(this)).GetPassword(inValue);
            return retVal.GetPasswordResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Moedelo.AstralV3.Client.AstralAuthServiceReference.GetPasswordResponse1> Moedelo.AstralV3.Client.AstralAuthServiceReference.AutorizationService.GetPasswordAsync(Moedelo.AstralV3.Client.AstralAuthServiceReference.GetPassword1 request) {
            return base.Channel.GetPasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<Moedelo.AstralV3.Client.AstralAuthServiceReference.GetPasswordResponse1> GetPasswordAsync(Moedelo.AstralV3.Client.AstralAuthServiceReference.AutorizationHeaderWithExtra AutorizationHeaderWithExtra, Moedelo.AstralV3.Client.AstralAuthServiceReference.GetPassword GetPassword) {
            Moedelo.AstralV3.Client.AstralAuthServiceReference.GetPassword1 inValue = new Moedelo.AstralV3.Client.AstralAuthServiceReference.GetPassword1();
            inValue.AutorizationHeaderWithExtra = AutorizationHeaderWithExtra;
            inValue.GetPassword = GetPassword;
            return ((Moedelo.AstralV3.Client.AstralAuthServiceReference.AutorizationService)(this)).GetPasswordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Moedelo.AstralV3.Client.AstralAuthServiceReference.GetSessionkeyByCertResponse1 Moedelo.AstralV3.Client.AstralAuthServiceReference.AutorizationService.GetSessionkeyByCert(Moedelo.AstralV3.Client.AstralAuthServiceReference.GetSessionkeyByCert1 request) {
            return base.Channel.GetSessionkeyByCert(request);
        }
        
        public Moedelo.AstralV3.Client.AstralAuthServiceReference.GetSessionkeyByCertResponse GetSessionkeyByCert(Moedelo.AstralV3.Client.AstralAuthServiceReference.GetSessionkeyByCert GetSessionkeyByCert1) {
            Moedelo.AstralV3.Client.AstralAuthServiceReference.GetSessionkeyByCert1 inValue = new Moedelo.AstralV3.Client.AstralAuthServiceReference.GetSessionkeyByCert1();
            inValue.GetSessionkeyByCert = GetSessionkeyByCert1;
            Moedelo.AstralV3.Client.AstralAuthServiceReference.GetSessionkeyByCertResponse1 retVal = ((Moedelo.AstralV3.Client.AstralAuthServiceReference.AutorizationService)(this)).GetSessionkeyByCert(inValue);
            return retVal.GetSessionkeyByCertResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Moedelo.AstralV3.Client.AstralAuthServiceReference.GetSessionkeyByCertResponse1> Moedelo.AstralV3.Client.AstralAuthServiceReference.AutorizationService.GetSessionkeyByCertAsync(Moedelo.AstralV3.Client.AstralAuthServiceReference.GetSessionkeyByCert1 request) {
            return base.Channel.GetSessionkeyByCertAsync(request);
        }
        
        public System.Threading.Tasks.Task<Moedelo.AstralV3.Client.AstralAuthServiceReference.GetSessionkeyByCertResponse1> GetSessionkeyByCertAsync(Moedelo.AstralV3.Client.AstralAuthServiceReference.GetSessionkeyByCert GetSessionkeyByCert) {
            Moedelo.AstralV3.Client.AstralAuthServiceReference.GetSessionkeyByCert1 inValue = new Moedelo.AstralV3.Client.AstralAuthServiceReference.GetSessionkeyByCert1();
            inValue.GetSessionkeyByCert = GetSessionkeyByCert;
            return ((Moedelo.AstralV3.Client.AstralAuthServiceReference.AutorizationService)(this)).GetSessionkeyByCertAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Moedelo.AstralV3.Client.AstralAuthServiceReference.GetEncryptedSessionkeyResponse1 Moedelo.AstralV3.Client.AstralAuthServiceReference.AutorizationService.GetEncryptedSessionkey(Moedelo.AstralV3.Client.AstralAuthServiceReference.GetEncryptedSessionkey1 request) {
            return base.Channel.GetEncryptedSessionkey(request);
        }
        
        public Moedelo.AstralV3.Client.AstralAuthServiceReference.GetEncryptedSessionkeyResponse GetEncryptedSessionkey(Moedelo.AstralV3.Client.AstralAuthServiceReference.GetEncryptedSessionkey GetEncryptedSessionkey1) {
            Moedelo.AstralV3.Client.AstralAuthServiceReference.GetEncryptedSessionkey1 inValue = new Moedelo.AstralV3.Client.AstralAuthServiceReference.GetEncryptedSessionkey1();
            inValue.GetEncryptedSessionkey = GetEncryptedSessionkey1;
            Moedelo.AstralV3.Client.AstralAuthServiceReference.GetEncryptedSessionkeyResponse1 retVal = ((Moedelo.AstralV3.Client.AstralAuthServiceReference.AutorizationService)(this)).GetEncryptedSessionkey(inValue);
            return retVal.GetEncryptedSessionkeyResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Moedelo.AstralV3.Client.AstralAuthServiceReference.GetEncryptedSessionkeyResponse1> Moedelo.AstralV3.Client.AstralAuthServiceReference.AutorizationService.GetEncryptedSessionkeyAsync(Moedelo.AstralV3.Client.AstralAuthServiceReference.GetEncryptedSessionkey1 request) {
            return base.Channel.GetEncryptedSessionkeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<Moedelo.AstralV3.Client.AstralAuthServiceReference.GetEncryptedSessionkeyResponse1> GetEncryptedSessionkeyAsync(Moedelo.AstralV3.Client.AstralAuthServiceReference.GetEncryptedSessionkey GetEncryptedSessionkey) {
            Moedelo.AstralV3.Client.AstralAuthServiceReference.GetEncryptedSessionkey1 inValue = new Moedelo.AstralV3.Client.AstralAuthServiceReference.GetEncryptedSessionkey1();
            inValue.GetEncryptedSessionkey = GetEncryptedSessionkey;
            return ((Moedelo.AstralV3.Client.AstralAuthServiceReference.AutorizationService)(this)).GetEncryptedSessionkeyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Moedelo.AstralV3.Client.AstralAuthServiceReference.GetPasswordBySkidResponse1 Moedelo.AstralV3.Client.AstralAuthServiceReference.AutorizationService.GetPasswordBySkid(Moedelo.AstralV3.Client.AstralAuthServiceReference.GetPasswordBySkid1 request) {
            return base.Channel.GetPasswordBySkid(request);
        }
        
        public Moedelo.AstralV3.Client.AstralAuthServiceReference.GetPasswordBySkidResponse GetPasswordBySkid(Moedelo.AstralV3.Client.AstralAuthServiceReference.AutorizationHeaderWithExtra AutorizationHeaderWithExtra, Moedelo.AstralV3.Client.AstralAuthServiceReference.GetPasswordBySkid GetPasswordBySkid1) {
            Moedelo.AstralV3.Client.AstralAuthServiceReference.GetPasswordBySkid1 inValue = new Moedelo.AstralV3.Client.AstralAuthServiceReference.GetPasswordBySkid1();
            inValue.AutorizationHeaderWithExtra = AutorizationHeaderWithExtra;
            inValue.GetPasswordBySkid = GetPasswordBySkid1;
            Moedelo.AstralV3.Client.AstralAuthServiceReference.GetPasswordBySkidResponse1 retVal = ((Moedelo.AstralV3.Client.AstralAuthServiceReference.AutorizationService)(this)).GetPasswordBySkid(inValue);
            return retVal.GetPasswordBySkidResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Moedelo.AstralV3.Client.AstralAuthServiceReference.GetPasswordBySkidResponse1> Moedelo.AstralV3.Client.AstralAuthServiceReference.AutorizationService.GetPasswordBySkidAsync(Moedelo.AstralV3.Client.AstralAuthServiceReference.GetPasswordBySkid1 request) {
            return base.Channel.GetPasswordBySkidAsync(request);
        }
        
        public System.Threading.Tasks.Task<Moedelo.AstralV3.Client.AstralAuthServiceReference.GetPasswordBySkidResponse1> GetPasswordBySkidAsync(Moedelo.AstralV3.Client.AstralAuthServiceReference.AutorizationHeaderWithExtra AutorizationHeaderWithExtra, Moedelo.AstralV3.Client.AstralAuthServiceReference.GetPasswordBySkid GetPasswordBySkid) {
            Moedelo.AstralV3.Client.AstralAuthServiceReference.GetPasswordBySkid1 inValue = new Moedelo.AstralV3.Client.AstralAuthServiceReference.GetPasswordBySkid1();
            inValue.AutorizationHeaderWithExtra = AutorizationHeaderWithExtra;
            inValue.GetPasswordBySkid = GetPasswordBySkid;
            return ((Moedelo.AstralV3.Client.AstralAuthServiceReference.AutorizationService)(this)).GetPasswordBySkidAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Moedelo.AstralV3.Client.AstralAuthServiceReference.GetSessionkeyBySMSResponse1 Moedelo.AstralV3.Client.AstralAuthServiceReference.AutorizationService.GetSessionkeyBySMS(Moedelo.AstralV3.Client.AstralAuthServiceReference.GetSessionkeyBySMS1 request) {
            return base.Channel.GetSessionkeyBySMS(request);
        }
        
        public Moedelo.AstralV3.Client.AstralAuthServiceReference.GetSessionkeyBySMSResponse GetSessionkeyBySMS(Moedelo.AstralV3.Client.AstralAuthServiceReference.GetSessionkeyBySMS GetSessionkeyBySMS1) {
            Moedelo.AstralV3.Client.AstralAuthServiceReference.GetSessionkeyBySMS1 inValue = new Moedelo.AstralV3.Client.AstralAuthServiceReference.GetSessionkeyBySMS1();
            inValue.GetSessionkeyBySMS = GetSessionkeyBySMS1;
            Moedelo.AstralV3.Client.AstralAuthServiceReference.GetSessionkeyBySMSResponse1 retVal = ((Moedelo.AstralV3.Client.AstralAuthServiceReference.AutorizationService)(this)).GetSessionkeyBySMS(inValue);
            return retVal.GetSessionkeyBySMSResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Moedelo.AstralV3.Client.AstralAuthServiceReference.GetSessionkeyBySMSResponse1> Moedelo.AstralV3.Client.AstralAuthServiceReference.AutorizationService.GetSessionkeyBySMSAsync(Moedelo.AstralV3.Client.AstralAuthServiceReference.GetSessionkeyBySMS1 request) {
            return base.Channel.GetSessionkeyBySMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<Moedelo.AstralV3.Client.AstralAuthServiceReference.GetSessionkeyBySMSResponse1> GetSessionkeyBySMSAsync(Moedelo.AstralV3.Client.AstralAuthServiceReference.GetSessionkeyBySMS GetSessionkeyBySMS) {
            Moedelo.AstralV3.Client.AstralAuthServiceReference.GetSessionkeyBySMS1 inValue = new Moedelo.AstralV3.Client.AstralAuthServiceReference.GetSessionkeyBySMS1();
            inValue.GetSessionkeyBySMS = GetSessionkeyBySMS;
            return ((Moedelo.AstralV3.Client.AstralAuthServiceReference.AutorizationService)(this)).GetSessionkeyBySMSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Moedelo.AstralV3.Client.AstralAuthServiceReference.DropSessionKeyResponse1 Moedelo.AstralV3.Client.AstralAuthServiceReference.AutorizationService.DropSessionKey(Moedelo.AstralV3.Client.AstralAuthServiceReference.DropSessionKey1 request) {
            return base.Channel.DropSessionKey(request);
        }
        
        public Moedelo.AstralV3.Client.AstralAuthServiceReference.DropSessionKeyResponse DropSessionKey(Moedelo.AstralV3.Client.AstralAuthServiceReference.RequestHeader RequestHeader, Moedelo.AstralV3.Client.AstralAuthServiceReference.DropSessionKey DropSessionKey1) {
            Moedelo.AstralV3.Client.AstralAuthServiceReference.DropSessionKey1 inValue = new Moedelo.AstralV3.Client.AstralAuthServiceReference.DropSessionKey1();
            inValue.RequestHeader = RequestHeader;
            inValue.DropSessionKey = DropSessionKey1;
            Moedelo.AstralV3.Client.AstralAuthServiceReference.DropSessionKeyResponse1 retVal = ((Moedelo.AstralV3.Client.AstralAuthServiceReference.AutorizationService)(this)).DropSessionKey(inValue);
            return retVal.DropSessionKeyResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Moedelo.AstralV3.Client.AstralAuthServiceReference.DropSessionKeyResponse1> Moedelo.AstralV3.Client.AstralAuthServiceReference.AutorizationService.DropSessionKeyAsync(Moedelo.AstralV3.Client.AstralAuthServiceReference.DropSessionKey1 request) {
            return base.Channel.DropSessionKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<Moedelo.AstralV3.Client.AstralAuthServiceReference.DropSessionKeyResponse1> DropSessionKeyAsync(Moedelo.AstralV3.Client.AstralAuthServiceReference.RequestHeader RequestHeader, Moedelo.AstralV3.Client.AstralAuthServiceReference.DropSessionKey DropSessionKey) {
            Moedelo.AstralV3.Client.AstralAuthServiceReference.DropSessionKey1 inValue = new Moedelo.AstralV3.Client.AstralAuthServiceReference.DropSessionKey1();
            inValue.RequestHeader = RequestHeader;
            inValue.DropSessionKey = DropSessionKey;
            return ((Moedelo.AstralV3.Client.AstralAuthServiceReference.AutorizationService)(this)).DropSessionKeyAsync(inValue);
        }
    }
}
