//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moedelo.CommonV2.Auth.OAuth2.DataAccess {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Queries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Queries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Moedelo.CommonV2.Auth.OAuth2.DataAccess.Queries", typeof(Queries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to declare @CheckResult bit = 0;
        ///
        ///if (exists ( select top 1 UFD.id
        ///								from dbo.UserFirmData as UFD
        ///								where UFD.id_user = @UserId
        ///										and UFD.id_firm = @FirmId ))
        ///begin
        ///		set @CheckResult = 1;
        ///end;
        ///
        ///select @CheckResult;.
        /// </summary>
        internal static string CheckUserFirmId {
            get {
                return ResourceManager.GetString("CheckUserFirmId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to declare @IsProfOutsource bit = 0;
        ///
        ///if (exists ( select top 1 u.id
        ///								from dbo.Users as u
        ///										inner join dbo.Account as a
        ///												on u.AccountId = a.Id
        ///								where u.id = @UserId
        ///										and (a.Type = 2
        ///										or (a.Type = 1
        ///										and @UserId &lt;&gt; a.MainAdminId)) ))
        ///begin
        ///		set @IsProfOutsource = 1;
        ///end;
        ///
        ///select @IsProfOutsource;.
        /// </summary>
        internal static string IsProfOutsourceOrLostAccount {
            get {
                return ResourceManager.GetString("IsProfOutsourceOrLostAccount", resourceCulture);
            }
        }
    }
}
