//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moedelo.AstralV3.Client.AstralFlcServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="tns", ConfigurationName="AstralFlcServiceReference.FlkService")]
    public interface FlkService {
        
        // CODEGEN: Generating message contract since the operation CheckFiles is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="CheckFiles", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Moedelo.AstralV3.Client.AstralFlcServiceReference.CheckFilesResponse1 CheckFiles(Moedelo.AstralV3.Client.AstralFlcServiceReference.CheckFiles1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="CheckFiles", ReplyAction="*")]
        System.Threading.Tasks.Task<Moedelo.AstralV3.Client.AstralFlcServiceReference.CheckFilesResponse1> CheckFilesAsync(Moedelo.AstralV3.Client.AstralFlcServiceReference.CheckFiles1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="tns")]
    public partial class CheckFiles : object, System.ComponentModel.INotifyPropertyChanged {
        
        private File[] filesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="https://iotchet.ru/namespases")]
        public File[] Files {
            get {
                return this.filesField;
            }
            set {
                this.filesField = value;
                this.RaisePropertyChanged("Files");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://iotchet.ru/namespases")]
    public partial class File : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string filenameField;
        
        private byte[] contentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string filename {
            get {
                return this.filenameField;
            }
            set {
                this.filenameField = value;
                this.RaisePropertyChanged("filename");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("content");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://iotchet.ru/namespases")]
    public partial class FLKResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusField;
        
        private byte[] protocolField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] protocol {
            get {
                return this.protocolField;
            }
            set {
                this.protocolField = value;
                this.RaisePropertyChanged("protocol");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="tns")]
    public partial class CheckFilesResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FLKResult resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public FLKResult Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckFiles1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="tns", Order=0)]
        public Moedelo.AstralV3.Client.AstralFlcServiceReference.CheckFiles CheckFiles;
        
        public CheckFiles1() {
        }
        
        public CheckFiles1(Moedelo.AstralV3.Client.AstralFlcServiceReference.CheckFiles CheckFiles) {
            this.CheckFiles = CheckFiles;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckFilesResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="tns", Order=0)]
        public Moedelo.AstralV3.Client.AstralFlcServiceReference.CheckFilesResponse CheckFilesResponse;
        
        public CheckFilesResponse1() {
        }
        
        public CheckFilesResponse1(Moedelo.AstralV3.Client.AstralFlcServiceReference.CheckFilesResponse CheckFilesResponse) {
            this.CheckFilesResponse = CheckFilesResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FlkServiceChannel : Moedelo.AstralV3.Client.AstralFlcServiceReference.FlkService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FlkServiceClient : System.ServiceModel.ClientBase<Moedelo.AstralV3.Client.AstralFlcServiceReference.FlkService>, Moedelo.AstralV3.Client.AstralFlcServiceReference.FlkService {
        
        public FlkServiceClient() {
        }
        
        public FlkServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FlkServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FlkServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FlkServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Moedelo.AstralV3.Client.AstralFlcServiceReference.CheckFilesResponse1 Moedelo.AstralV3.Client.AstralFlcServiceReference.FlkService.CheckFiles(Moedelo.AstralV3.Client.AstralFlcServiceReference.CheckFiles1 request) {
            return base.Channel.CheckFiles(request);
        }
        
        public Moedelo.AstralV3.Client.AstralFlcServiceReference.CheckFilesResponse CheckFiles(Moedelo.AstralV3.Client.AstralFlcServiceReference.CheckFiles CheckFiles1) {
            Moedelo.AstralV3.Client.AstralFlcServiceReference.CheckFiles1 inValue = new Moedelo.AstralV3.Client.AstralFlcServiceReference.CheckFiles1();
            inValue.CheckFiles = CheckFiles1;
            Moedelo.AstralV3.Client.AstralFlcServiceReference.CheckFilesResponse1 retVal = ((Moedelo.AstralV3.Client.AstralFlcServiceReference.FlkService)(this)).CheckFiles(inValue);
            return retVal.CheckFilesResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Moedelo.AstralV3.Client.AstralFlcServiceReference.CheckFilesResponse1> Moedelo.AstralV3.Client.AstralFlcServiceReference.FlkService.CheckFilesAsync(Moedelo.AstralV3.Client.AstralFlcServiceReference.CheckFiles1 request) {
            return base.Channel.CheckFilesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Moedelo.AstralV3.Client.AstralFlcServiceReference.CheckFilesResponse1> CheckFilesAsync(Moedelo.AstralV3.Client.AstralFlcServiceReference.CheckFiles CheckFiles) {
            Moedelo.AstralV3.Client.AstralFlcServiceReference.CheckFiles1 inValue = new Moedelo.AstralV3.Client.AstralFlcServiceReference.CheckFiles1();
            inValue.CheckFiles = CheckFiles;
            return ((Moedelo.AstralV3.Client.AstralFlcServiceReference.FlkService)(this)).CheckFilesAsync(inValue);
        }
    }
}
