//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moedelo.AstralV3.Client.AstralExternalServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://regoffice.org/", ConfigurationName="AstralExternalServiceReference.ExternalServiceSoap")]
    public interface ExternalServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regoffice.org/Authorisation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Authorisation(string login, string password, string appId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regoffice.org/Authorisation", ReplyAction="*")]
        System.Threading.Tasks.Task<string> AuthorisationAsync(string login, string password, string appId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regoffice.org/GetProductExportInfoList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Moedelo.AstralV3.Client.AstralExternalServiceReference.ProductExportInfo[] GetProductExportInfoList(string subjectKeyId, string serialNumber, string inn, string kpp, string guid, string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regoffice.org/GetProductExportInfoList", ReplyAction="*")]
        System.Threading.Tasks.Task<Moedelo.AstralV3.Client.AstralExternalServiceReference.ProductExportInfo[]> GetProductExportInfoListAsync(string subjectKeyId, string serialNumber, string inn, string kpp, string guid, string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regoffice.org/CheckProductGuid", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool CheckProductGuid(string guid, string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regoffice.org/CheckProductGuid", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> CheckProductGuidAsync(string guid, string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regoffice.org/AuthorisationJson", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string AuthorisationJson(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regoffice.org/AuthorisationJson", ReplyAction="*")]
        System.Threading.Tasks.Task<string> AuthorisationJsonAsync(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regoffice.org/HelloWord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWord();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regoffice.org/HelloWord", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWordAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regoffice.org/HelloWordSession", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWordSession();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regoffice.org/HelloWordSession", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWordSessionAsync();
        
        // CODEGEN: Parameter 'certData' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://regoffice.org/GetHtmlCertView", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Moedelo.AstralV3.Client.AstralExternalServiceReference.GetHtmlCertViewResponse GetHtmlCertView(Moedelo.AstralV3.Client.AstralExternalServiceReference.GetHtmlCertViewRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regoffice.org/GetHtmlCertView", ReplyAction="*")]
        System.Threading.Tasks.Task<Moedelo.AstralV3.Client.AstralExternalServiceReference.GetHtmlCertViewResponse> GetHtmlCertViewAsync(Moedelo.AstralV3.Client.AstralExternalServiceReference.GetHtmlCertViewRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regoffice.org/ExportCertPrintForm", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ExportCertPrintForm(string productGuid, string login, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regoffice.org/ExportCertPrintForm", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ExportCertPrintFormAsync(string productGuid, string login, string pass);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://regoffice.org/")]
    public partial class ProductExportInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string shortNameField;
        
        private string fullNameField;
        
        private string innField;
        
        private string kppField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string patronymicField;
        
        private ClientContactPerson[] contactPeopleField;
        
        private string emailField;
        
        private System.Guid guidField;
        
        private string serialNumberField;
        
        private string subjectKeyIdField;
        
        private System.Nullable<System.DateTime> certificateEndDateField;
        
        private System.Nullable<System.DateTime> certificateBeginDateField;
        
        private System.Nullable<System.DateTime> licenseEndDateField;
        
        private string productTypeNameField;
        
        private System.Nullable<System.DateTime> tariffInitialDateField;
        
        private System.Nullable<System.DateTime> tariffEndDateField;
        
        private string tariffNameField;
        
        private decimal tariffPriceField;
        
        private string officeNameField;
        
        private string snilsField;
        
        private int genderField;
        
        private System.Nullable<System.DateTime> birthDateField;
        
        private string birthPlaceField;
        
        private string passportTypeField;
        
        private string pasportSeriesField;
        
        private string passportNumberField;
        
        private string passportAddonField;
        
        private string passportUnitField;
        
        private System.Nullable<System.DateTime> passportDateField;
        
        private string countryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ShortName {
            get {
                return this.shortNameField;
            }
            set {
                this.shortNameField = value;
                this.RaisePropertyChanged("ShortName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
                this.RaisePropertyChanged("FullName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Inn {
            get {
                return this.innField;
            }
            set {
                this.innField = value;
                this.RaisePropertyChanged("Inn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Kpp {
            get {
                return this.kppField;
            }
            set {
                this.kppField = value;
                this.RaisePropertyChanged("Kpp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("LastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Patronymic {
            get {
                return this.patronymicField;
            }
            set {
                this.patronymicField = value;
                this.RaisePropertyChanged("Patronymic");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=7)]
        public ClientContactPerson[] ContactPeople {
            get {
                return this.contactPeopleField;
            }
            set {
                this.contactPeopleField = value;
                this.RaisePropertyChanged("ContactPeople");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public System.Guid Guid {
            get {
                return this.guidField;
            }
            set {
                this.guidField = value;
                this.RaisePropertyChanged("Guid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string SerialNumber {
            get {
                return this.serialNumberField;
            }
            set {
                this.serialNumberField = value;
                this.RaisePropertyChanged("SerialNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string SubjectKeyId {
            get {
                return this.subjectKeyIdField;
            }
            set {
                this.subjectKeyIdField = value;
                this.RaisePropertyChanged("SubjectKeyId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<System.DateTime> CertificateEndDate {
            get {
                return this.certificateEndDateField;
            }
            set {
                this.certificateEndDateField = value;
                this.RaisePropertyChanged("CertificateEndDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<System.DateTime> CertificateBeginDate {
            get {
                return this.certificateBeginDateField;
            }
            set {
                this.certificateBeginDateField = value;
                this.RaisePropertyChanged("CertificateBeginDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public System.Nullable<System.DateTime> LicenseEndDate {
            get {
                return this.licenseEndDateField;
            }
            set {
                this.licenseEndDateField = value;
                this.RaisePropertyChanged("LicenseEndDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string ProductTypeName {
            get {
                return this.productTypeNameField;
            }
            set {
                this.productTypeNameField = value;
                this.RaisePropertyChanged("ProductTypeName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public System.Nullable<System.DateTime> TariffInitialDate {
            get {
                return this.tariffInitialDateField;
            }
            set {
                this.tariffInitialDateField = value;
                this.RaisePropertyChanged("TariffInitialDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public System.Nullable<System.DateTime> TariffEndDate {
            get {
                return this.tariffEndDateField;
            }
            set {
                this.tariffEndDateField = value;
                this.RaisePropertyChanged("TariffEndDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string TariffName {
            get {
                return this.tariffNameField;
            }
            set {
                this.tariffNameField = value;
                this.RaisePropertyChanged("TariffName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public decimal TariffPrice {
            get {
                return this.tariffPriceField;
            }
            set {
                this.tariffPriceField = value;
                this.RaisePropertyChanged("TariffPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string OfficeName {
            get {
                return this.officeNameField;
            }
            set {
                this.officeNameField = value;
                this.RaisePropertyChanged("OfficeName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string Snils {
            get {
                return this.snilsField;
            }
            set {
                this.snilsField = value;
                this.RaisePropertyChanged("Snils");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public int Gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
                this.RaisePropertyChanged("Gender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=23)]
        public System.Nullable<System.DateTime> BirthDate {
            get {
                return this.birthDateField;
            }
            set {
                this.birthDateField = value;
                this.RaisePropertyChanged("BirthDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string BirthPlace {
            get {
                return this.birthPlaceField;
            }
            set {
                this.birthPlaceField = value;
                this.RaisePropertyChanged("BirthPlace");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string PassportType {
            get {
                return this.passportTypeField;
            }
            set {
                this.passportTypeField = value;
                this.RaisePropertyChanged("PassportType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string PasportSeries {
            get {
                return this.pasportSeriesField;
            }
            set {
                this.pasportSeriesField = value;
                this.RaisePropertyChanged("PasportSeries");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string PassportNumber {
            get {
                return this.passportNumberField;
            }
            set {
                this.passportNumberField = value;
                this.RaisePropertyChanged("PassportNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string PassportAddon {
            get {
                return this.passportAddonField;
            }
            set {
                this.passportAddonField = value;
                this.RaisePropertyChanged("PassportAddon");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string PassportUnit {
            get {
                return this.passportUnitField;
            }
            set {
                this.passportUnitField = value;
                this.RaisePropertyChanged("PassportUnit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=30)]
        public System.Nullable<System.DateTime> PassportDate {
            get {
                return this.passportDateField;
            }
            set {
                this.passportDateField = value;
                this.RaisePropertyChanged("PassportDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("Country");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://regoffice.org/")]
    public partial class ClientContactPerson : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string phoneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
                this.RaisePropertyChanged("phone");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetHtmlCertView", WrapperNamespace="http://regoffice.org/", IsWrapped=true)]
    public partial class GetHtmlCertViewRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://regoffice.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] certData;
        
        public GetHtmlCertViewRequest() {
        }
        
        public GetHtmlCertViewRequest(byte[] certData) {
            this.certData = certData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetHtmlCertViewResponse", WrapperNamespace="http://regoffice.org/", IsWrapped=true)]
    public partial class GetHtmlCertViewResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://regoffice.org/", Order=0)]
        public string GetHtmlCertViewResult;
        
        public GetHtmlCertViewResponse() {
        }
        
        public GetHtmlCertViewResponse(string GetHtmlCertViewResult) {
            this.GetHtmlCertViewResult = GetHtmlCertViewResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ExternalServiceSoapChannel : Moedelo.AstralV3.Client.AstralExternalServiceReference.ExternalServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExternalServiceSoapClient : System.ServiceModel.ClientBase<Moedelo.AstralV3.Client.AstralExternalServiceReference.ExternalServiceSoap>, Moedelo.AstralV3.Client.AstralExternalServiceReference.ExternalServiceSoap {
        
        public ExternalServiceSoapClient() {
        }
        
        public ExternalServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExternalServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExternalServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExternalServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Authorisation(string login, string password, string appId) {
            return base.Channel.Authorisation(login, password, appId);
        }
        
        public System.Threading.Tasks.Task<string> AuthorisationAsync(string login, string password, string appId) {
            return base.Channel.AuthorisationAsync(login, password, appId);
        }
        
        public Moedelo.AstralV3.Client.AstralExternalServiceReference.ProductExportInfo[] GetProductExportInfoList(string subjectKeyId, string serialNumber, string inn, string kpp, string guid, string login, string password) {
            return base.Channel.GetProductExportInfoList(subjectKeyId, serialNumber, inn, kpp, guid, login, password);
        }
        
        public System.Threading.Tasks.Task<Moedelo.AstralV3.Client.AstralExternalServiceReference.ProductExportInfo[]> GetProductExportInfoListAsync(string subjectKeyId, string serialNumber, string inn, string kpp, string guid, string login, string password) {
            return base.Channel.GetProductExportInfoListAsync(subjectKeyId, serialNumber, inn, kpp, guid, login, password);
        }
        
        public bool CheckProductGuid(string guid, string login, string password) {
            return base.Channel.CheckProductGuid(guid, login, password);
        }
        
        public System.Threading.Tasks.Task<bool> CheckProductGuidAsync(string guid, string login, string password) {
            return base.Channel.CheckProductGuidAsync(guid, login, password);
        }
        
        public string AuthorisationJson(string login, string password) {
            return base.Channel.AuthorisationJson(login, password);
        }
        
        public System.Threading.Tasks.Task<string> AuthorisationJsonAsync(string login, string password) {
            return base.Channel.AuthorisationJsonAsync(login, password);
        }
        
        public string HelloWord() {
            return base.Channel.HelloWord();
        }
        
        public System.Threading.Tasks.Task<string> HelloWordAsync() {
            return base.Channel.HelloWordAsync();
        }
        
        public string HelloWordSession() {
            return base.Channel.HelloWordSession();
        }
        
        public System.Threading.Tasks.Task<string> HelloWordSessionAsync() {
            return base.Channel.HelloWordSessionAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Moedelo.AstralV3.Client.AstralExternalServiceReference.GetHtmlCertViewResponse Moedelo.AstralV3.Client.AstralExternalServiceReference.ExternalServiceSoap.GetHtmlCertView(Moedelo.AstralV3.Client.AstralExternalServiceReference.GetHtmlCertViewRequest request) {
            return base.Channel.GetHtmlCertView(request);
        }
        
        public string GetHtmlCertView(byte[] certData) {
            Moedelo.AstralV3.Client.AstralExternalServiceReference.GetHtmlCertViewRequest inValue = new Moedelo.AstralV3.Client.AstralExternalServiceReference.GetHtmlCertViewRequest();
            inValue.certData = certData;
            Moedelo.AstralV3.Client.AstralExternalServiceReference.GetHtmlCertViewResponse retVal = ((Moedelo.AstralV3.Client.AstralExternalServiceReference.ExternalServiceSoap)(this)).GetHtmlCertView(inValue);
            return retVal.GetHtmlCertViewResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Moedelo.AstralV3.Client.AstralExternalServiceReference.GetHtmlCertViewResponse> Moedelo.AstralV3.Client.AstralExternalServiceReference.ExternalServiceSoap.GetHtmlCertViewAsync(Moedelo.AstralV3.Client.AstralExternalServiceReference.GetHtmlCertViewRequest request) {
            return base.Channel.GetHtmlCertViewAsync(request);
        }
        
        public System.Threading.Tasks.Task<Moedelo.AstralV3.Client.AstralExternalServiceReference.GetHtmlCertViewResponse> GetHtmlCertViewAsync(byte[] certData) {
            Moedelo.AstralV3.Client.AstralExternalServiceReference.GetHtmlCertViewRequest inValue = new Moedelo.AstralV3.Client.AstralExternalServiceReference.GetHtmlCertViewRequest();
            inValue.certData = certData;
            return ((Moedelo.AstralV3.Client.AstralExternalServiceReference.ExternalServiceSoap)(this)).GetHtmlCertViewAsync(inValue);
        }
        
        public string ExportCertPrintForm(string productGuid, string login, string pass) {
            return base.Channel.ExportCertPrintForm(productGuid, login, pass);
        }
        
        public System.Threading.Tasks.Task<string> ExportCertPrintFormAsync(string productGuid, string login, string pass) {
            return base.Channel.ExportCertPrintFormAsync(productGuid, login, pass);
        }
    }
}
