//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moedelo.Finances.DataAccess.Money.Tables {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TableQueries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TableQueries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Moedelo.Finances.DataAccess.Money.Tables.TableQueries", typeof(TableQueries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with operations
        ///as (select po.DocumentBaseId,
        ///           po.Date,
        ///           po.PaymentNumber as Number,
        ///           po.Direction,
        ///           po.KontragentName,
        ///           po.OperationType,
        ///           po.Sum,
        ///           sa.id_currency as Currency,
        ///           sa.SettlementAccountType as SettlementType,
        ///           po.Description
        ///    from dbo.Accounting_PaymentOrder as po
        ///        join dbo.SettlementAccount as sa
        ///            on sa.id = po.SettlementAccountId
        ///    where po.FirmId = @FirmId
        ///          and isnull(po. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetImported {
            get {
                return ResourceManager.GetString("GetImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select count(1)
        ///	from dbo.Accounting_PaymentOrder
        ///	where FirmId = @FirmId
        ///		and isnull(OperationState, @RegularOperationState) = @ImportedOperationState
        ///		and isnull(OutsourceState, 0) &lt;&gt; @UnconfirmedOutsourceState
        ///		and (@SourceId is null or SettlementAccountId = @SourceId);
        ///.
        /// </summary>
        internal static string GetImportedOperationCount {
            get {
                return ResourceManager.GetString("GetImportedOperationCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set nocount on;
        ///set tran isolation level read uncommitted;
        ///
        ///set @StartDate = iif(@StartDate &lt; @InitialDate, @InitialDate, isnull(@StartDate, @InitialDate));
        ///declare @StartSummaryDate date = iif(@StartDate &lt; @InitialSummaryDate , @InitialSummaryDate , isnull(@StartDate, @InitialSummaryDate));
        ///declare @TurnoverStartDate date = iif(@StartSummaryDate &lt; @TodayStart, @StartSummaryDate, @TodayStart);
        ///declare @TurnoverEndDate datetime = iif(@EndDate &lt; @TodayEnd, @EndDate, @TodayEnd);
        ///
        /// /* BudgetaryTypeFilter
        ///select  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetMain {
            get {
                return ResourceManager.GetString("GetMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;with
        /// /* BudgetaryTypeExtraFilter
        ///BudgetaryTypeExtraFilterKbkId as (select
        ///    KbkNumber.Id
        ///from dbo.KbkNumber 
        ///where KbkNumber.AccountCode &gt;= @StartAccountCode 
        ///    and KbkNumber.AccountCode &lt; @EndAccountCode
        ///    and KbkNumber.KbkType 
        ///    /* AllInsuranceFeeFilter
        ///    not 
        ///    AllInsuranceFeeFilter */
        ///    in (select Id from @FixedFeesKbkTypes)
        ///),
        ///BudgetaryTypeExtraFilter */
        ///operations as (select po.Id,
        ///           po.DocumentBaseId,
        ///           po.Date,
        ///           po.ModifyDate,
        ///           po.PaymentNumber a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetOutsourceProcessing {
            get {
                return ResourceManager.GetString("GetOutsourceProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with operations
        ///as (select po.DocumentBaseId,
        ///           po.Date,
        ///           po.PaymentNumber as Number,
        ///           po.Direction,
        ///           po.KontragentName,
        ///           po.OperationType,
        ///           po.OperationState,
        ///           po.Sum,
        ///           sa.id_currency as Currency,
        ///           po.Description,
        ///           bpo.DocumentBaseId as BaseOperationId
        ///    from dbo.Accounting_PaymentOrder as po
        ///        join dbo.SettlementAccount as sa
        ///            on sa.id = po.SettlementAccountId
        ///        left join dbo.Account [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetUnrecognized {
            get {
                return ResourceManager.GetString("GetUnrecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select count(1)
        ///	from dbo.Accounting_PaymentOrder
        ///	where FirmId = @FirmId
        ///		and isnull(OperationState, @RegularOperationState) in (select Id from @UnrecognizedOperationStates)
        ///		and isnull(OutsourceState, 0) &lt;&gt; @UnconfirmedOutsourceState
        ///		and (@SourceId is null or SettlementAccountId = @SourceId);
        ///.
        /// </summary>
        internal static string GetUnrecognizedOperationCount {
            get {
                return ResourceManager.GetString("GetUnrecognizedOperationCount", resourceCulture);
            }
        }
    }
}
