//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moedelo.Finances.DataAccess.Money.Operations.MoneyTransfers {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MoneyTransferOperationQeries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MoneyTransferOperationQeries() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Moedelo.Finances.DataAccess.Money.Operations.MoneyTransfers.MoneyTransferOperatio" +
                            "nQeries", typeof(MoneyTransferOperationQeries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на declare @ids dbo.IntList;
        ///insert into @ids(Id)
        ///	select id from dbo.FinancialOperation
        ///		where firm_id = @FirmId
        ///			and DocumentBaseId in (select Id from @BaseIds);
        ///delete from dbo.MoneyTransferOperation
        ///	where id in (select Id from @ids);
        ///delete from dbo.FinancialOperation
        ///	where id in (select Id from @ids);
        ///
        ///.
        /// </summary>
        internal static string DeleteByBaseIds {
            get {
                return ResourceManager.GetString("DeleteByBaseIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на select /* TopConstraint */
        ///	fo.Id,
        ///	fo.DocumentBaseId,
        ///	fo.operation_date as Date,
        ///	mto.number_of_document as Number,
        ///	case
        ///		when mtot.type = 1 then 2
        ///		when mtot.type = 2 then 1
        ///		when mtot.type = 3
        ///			and fo.type = &apos;MovementFromSettlementToCashMoneyTransferOperation&apos; then 1
        ///		when mtot.type = 3
        ///			and fo.type = &apos;MovementFromCashToSettlementMoneyTransferOperation&apos; then 2
        ///		when mtot.type = 3
        ///			and fo.type = &apos;MovementFromPurseToSettlementMoneyTransferOperation&apos; then 2
        ///		when mtot.type = 3
        ///	 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string GetByFirm {
            get {
                return ResourceManager.GetString("GetByFirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на select
        ///	f.FirmId,
        ///	convert(bit, iif(max(fo.operation_date) is not null, 1, 0))	as IsBalanceSetted
        ///	from #FirmIds as f
        ///		left outer join dbo.FinancialOperation as fo on
        ///			f.FirmId = fo.firm_id
        ///	group by f.FirmId;.
        /// </summary>
        internal static string GetIsBalanceSettedForFirms {
            get {
                return ResourceManager.GetString("GetIsBalanceSettedForFirms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на if exists (select 1
        ///			from dbo.FinancialOperation as fo
        ///				join dbo.MoneyTransferOperation as mto
        ///					on mto.id = fo.id
        ///			where fo.firm_id = @FirmId
        ///				and fo.type &lt;&gt; &apos;CurrencyBalanceOperation&apos;
        ///				and mto.SettlementAccountId = @SettlementAccountId)
        ///	select 1;
        ///else
        ///	select 0;
        ///.
        /// </summary>
        internal static string HasOperationsBySettlementAccount {
            get {
                return ResourceManager.GetString("HasOperationsBySettlementAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на insert into dbo.FinancialOperation
        ///(
        ///	firm_id,
        ///	type,
        ///	des,
        ///	number,
        ///	operation_date,
        ///	DocumentBaseId,
        ///	TaxPostingType)
        ///values
        ///(
        ///	@FirmId,
        ///	@OperationType,
        ///	&apos;&apos;,			-- des
        ///	@Number,
        ///	@Date,
        ///	@DocumentBaseId,
        ///	0 -- TaxPostingType - smallint
        ///);
        ///declare @foId int = scope_identity();
        ///
        ///insert into dbo.MoneyTransferOperation
        ///(
        ///	id,
        ///	money_bay_type,
        ///	number_of_document,
        ///	SettlementAccountId,
        ///	summ)
        ///values
        ///(
        ///	@foId,
        ///	@Number,
        ///	@MoneyBayType,
        ///	@SettlementAccountId,
        ///	@Sum
        ///);
        ///select @ [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на select top (@count)
        ///	mto.kontragent_id as KontragentId,
        ///	cast(sum(mto.summ) as decimal(20, 4))  as TotalSum
        ///from dbo.MoneyTransferOperation as mto
        ///	left join dbo.FinancialOperation as fo
        ///		on fo.id = mto.id
        ///where fo.firm_id = @firmId
        ///	and fo.operation_date between @startDate and @endDate
        ///	and mto.kontragent_id is not null
        ///group by mto.kontragent_id
        ///order by TotalSum desc.
        /// </summary>
        internal static string TopByOperationsWithKontragents {
            get {
                return ResourceManager.GetString("TopByOperationsWithKontragents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на update dbo.FinancialOperation
        ///	set
        ///		operation_date = @Date,
        ///		number = @Number,
        ///		DocumentBaseId = @DocumentBaseId
        ///	where id = @Id;
        ///
        ///update dbo.MoneyTransferOperation
        ///	set
        ///		number_of_document = @Number,
        ///		money_bay_type = @MoneyBayType,
        ///		SettlementAccountId = @SettlementAccountId,
        ///		summ = @Sum
        ///	where id = @Id;
        ///.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
    }
}
