//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moedelo.Money.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PaymentOrdersDescriptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PaymentOrdersDescriptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Moedelo.Money.Resources.PaymentOrdersDescriptions", typeof(PaymentOrdersDescriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выплата по агентскому договору. НДС не облагается..
        /// </summary>
        public static string AgencyContract {
            get {
                return ResourceManager.GetString("AgencyContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Взнос собственных средств. НДС не облагается..
        /// </summary>
        public static string ContributionOfOwnFunds {
            get {
                return ResourceManager.GetString("ContributionOfOwnFunds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выдача займа. НДС не облагается..
        /// </summary>
        public static string LoanIssue {
            get {
                return ResourceManager.GetString("LoanIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Погашение займа. НДС не облагается..
        /// </summary>
        public static string LoanRepayment {
            get {
                return ResourceManager.GetString("LoanRepayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выплата подотчетному лицу. НДС не облагается..
        /// </summary>
        public static string PaymentToAccountablePerson {
            get {
                return ResourceManager.GetString("PaymentToAccountablePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выплата физлицам. НДС не облагается..
        /// </summary>
        public static string PaymentToNaturalPersons {
            get {
                return ResourceManager.GetString("PaymentToNaturalPersons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оплата контрагенту. НДС не облагается..
        /// </summary>
        public static string PaymentToSupplier {
            get {
                return ResourceManager.GetString("PaymentToSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возврат денег клиенту. НДС не облагается..
        /// </summary>
        public static string RefundToCustomer {
            get {
                return ResourceManager.GetString("RefundToCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лизинговый платеж. НДС не облагается..
        /// </summary>
        public static string RentPayment {
            get {
                return ResourceManager.GetString("RentPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перевод на другой счет. НДС не облагается..
        /// </summary>
        public static string TransferToAccount {
            get {
                return ResourceManager.GetString("TransferToAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Снятие с расчетного счета. НДС не облагается..
        /// </summary>
        public static string WithdrawalFromAccount {
            get {
                return ResourceManager.GetString("WithdrawalFromAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перевод прибыли от предпринимательской деятельности..
        /// </summary>
        public static string WithdrawalOfProfit {
            get {
                return ResourceManager.GetString("WithdrawalOfProfit", resourceCulture);
            }
        }
    }
}
