//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moedelo.AstralV3.Client.AstralRegServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://regservice.keydisk.ru/", ConfigurationName="AstralRegServiceRef.RegServiceSoap")]
    public interface RegServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regservice.keydisk.ru/SendPacket", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SendPacket(string packet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regservice.keydisk.ru/SendPacket", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SendPacketAsync(string packet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regservice.keydisk.ru/SendPacketWithTicket", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SendPacketWithTicket(string packet, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regservice.keydisk.ru/SendPacketWithTicket", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SendPacketWithTicketAsync(string packet, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regservice.keydisk.ru/ReceiveUpdatedPacket", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ReceiveUpdatedPacket(string packetId, string updateDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regservice.keydisk.ru/ReceiveUpdatedPacket", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ReceiveUpdatedPacketAsync(string packetId, string updateDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regservice.keydisk.ru/ReceivePacket", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ReceivePacket(string packetId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regservice.keydisk.ru/ReceivePacket", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ReceivePacketAsync(string packetId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regservice.keydisk.ru/GetThumbPrintForRecipient", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetThumbPrintForRecipient(int protocol, string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regservice.keydisk.ru/GetThumbPrintForRecipient", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetThumbPrintForRecipientAsync(int protocol, string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regservice.keydisk.ru/GetCertificateForRecipient", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetCertificateForRecipient(int protocol, string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regservice.keydisk.ru/GetCertificateForRecipient", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetCertificateForRecipientAsync(int protocol, string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regservice.keydisk.ru/SendCertRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SendCertRequest(string packId, string certRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regservice.keydisk.ru/SendCertRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SendCertRequestAsync(string packId, string certRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regservice.keydisk.ru/SendMobile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SendMobile(string id, string mobile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regservice.keydisk.ru/SendMobile", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SendMobileAsync(string id, string mobile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regservice.keydisk.ru/Test", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Test(string file);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regservice.keydisk.ru/Test", ReplyAction="*")]
        System.Threading.Tasks.Task<string> TestAsync(string file);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regservice.keydisk.ru/GetCemposRecipientList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetCemposRecipientList(string regionCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regservice.keydisk.ru/GetCemposRecipientList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetCemposRecipientListAsync(string regionCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regservice.keydisk.ru/GetRoutePfrList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetRoutePfrList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regservice.keydisk.ru/GetRoutePfrList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetRoutePfrListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regservice.keydisk.ru/GetProductList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetProductList(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regservice.keydisk.ru/GetProductList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetProductListAsync(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regservice.keydisk.ru/GetWorkflowProductUidList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetWorkflowProductUidList(string workflowGuidsString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regservice.keydisk.ru/GetWorkflowProductUidList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetWorkflowProductUidListAsync(string workflowGuidsString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regservice.keydisk.ru/GetPfrLayoutCodes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetPfrLayoutCodes(string regionCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regservice.keydisk.ru/GetPfrLayoutCodes", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetPfrLayoutCodesAsync(string regionCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regservice.keydisk.ru/GetFnsCodes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetFnsCodes(string regionCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regservice.keydisk.ru/GetFnsCodes", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetFnsCodesAsync(string regionCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regservice.keydisk.ru/GetPfrCodes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetPfrCodes(string regionCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regservice.keydisk.ru/GetPfrCodes", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetPfrCodesAsync(string regionCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regservice.keydisk.ru/GetStatCodes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetStatCodes(string regionCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regservice.keydisk.ru/GetStatCodes", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetStatCodesAsync(string regionCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regservice.keydisk.ru/ReceiveResponse", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ReceiveResponse(string packetId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regservice.keydisk.ru/ReceiveResponse", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ReceiveResponseAsync(string packetId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regservice.keydisk.ru/GetPriceInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetPriceInfo(int priceTypeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regservice.keydisk.ru/GetPriceInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetPriceInfoAsync(int priceTypeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regservice.keydisk.ru/GetBgRequestList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetBgRequestList(string inn, string kpp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regservice.keydisk.ru/GetBgRequestList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetBgRequestListAsync(string inn, string kpp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regservice.keydisk.ru/GetHtmlFromCertificate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetHtmlFromCertificate(string cert, int template);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regservice.keydisk.ru/GetHtmlFromCertificate", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetHtmlFromCertificateAsync(string cert, int template);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regservice.keydisk.ru/SignMessage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SignMessage(string id, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regservice.keydisk.ru/SignMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SignMessageAsync(string id, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regservice.keydisk.ru/EncryptMessage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string EncryptMessage(string id, string message, string certificates);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regservice.keydisk.ru/EncryptMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<string> EncryptMessageAsync(string id, string message, string certificates);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regservice.keydisk.ru/DecryptMessage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string DecryptMessage(string id, string encryptedMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regservice.keydisk.ru/DecryptMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<string> DecryptMessageAsync(string id, string encryptedMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regservice.keydisk.ru/GetSessionKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetSessionKey(string id, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regservice.keydisk.ru/GetSessionKey", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetSessionKeyAsync(string id, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regservice.keydisk.ru/GetNpf", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetNpf(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regservice.keydisk.ru/GetNpf", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetNpfAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regservice.keydisk.ru/VerifySign", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string VerifySign(string sign, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regservice.keydisk.ru/VerifySign", ReplyAction="*")]
        System.Threading.Tasks.Task<string> VerifySignAsync(string sign, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regservice.keydisk.ru/VerifyCert", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string VerifyCert(string cert);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regservice.keydisk.ru/VerifyCert", ReplyAction="*")]
        System.Threading.Tasks.Task<string> VerifyCertAsync(string cert);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regservice.keydisk.ru/SendTemplate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SendTemplate(string template);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regservice.keydisk.ru/SendTemplate", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SendTemplateAsync(string template);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regservice.keydisk.ru/GetCryptoProTemplateOid", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetCryptoProTemplateOid();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regservice.keydisk.ru/GetCryptoProTemplateOid", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetCryptoProTemplateOidAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regservice.keydisk.ru/GetCertificateSettings", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetCertificateSettings();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://regservice.keydisk.ru/GetCertificateSettings", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetCertificateSettingsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RegServiceSoapChannel : Moedelo.AstralV3.Client.AstralRegServiceRef.RegServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegServiceSoapClient : System.ServiceModel.ClientBase<Moedelo.AstralV3.Client.AstralRegServiceRef.RegServiceSoap>, Moedelo.AstralV3.Client.AstralRegServiceRef.RegServiceSoap {
        
        public RegServiceSoapClient() {
        }
        
        public RegServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RegServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SendPacket(string packet) {
            return base.Channel.SendPacket(packet);
        }
        
        public System.Threading.Tasks.Task<string> SendPacketAsync(string packet) {
            return base.Channel.SendPacketAsync(packet);
        }
        
        public string SendPacketWithTicket(string packet, string ticket) {
            return base.Channel.SendPacketWithTicket(packet, ticket);
        }
        
        public System.Threading.Tasks.Task<string> SendPacketWithTicketAsync(string packet, string ticket) {
            return base.Channel.SendPacketWithTicketAsync(packet, ticket);
        }
        
        public string ReceiveUpdatedPacket(string packetId, string updateDate) {
            return base.Channel.ReceiveUpdatedPacket(packetId, updateDate);
        }
        
        public System.Threading.Tasks.Task<string> ReceiveUpdatedPacketAsync(string packetId, string updateDate) {
            return base.Channel.ReceiveUpdatedPacketAsync(packetId, updateDate);
        }
        
        public string ReceivePacket(string packetId) {
            return base.Channel.ReceivePacket(packetId);
        }
        
        public System.Threading.Tasks.Task<string> ReceivePacketAsync(string packetId) {
            return base.Channel.ReceivePacketAsync(packetId);
        }
        
        public string GetThumbPrintForRecipient(int protocol, string code) {
            return base.Channel.GetThumbPrintForRecipient(protocol, code);
        }
        
        public System.Threading.Tasks.Task<string> GetThumbPrintForRecipientAsync(int protocol, string code) {
            return base.Channel.GetThumbPrintForRecipientAsync(protocol, code);
        }
        
        public string GetCertificateForRecipient(int protocol, string code) {
            return base.Channel.GetCertificateForRecipient(protocol, code);
        }
        
        public System.Threading.Tasks.Task<string> GetCertificateForRecipientAsync(int protocol, string code) {
            return base.Channel.GetCertificateForRecipientAsync(protocol, code);
        }
        
        public string SendCertRequest(string packId, string certRequest) {
            return base.Channel.SendCertRequest(packId, certRequest);
        }
        
        public System.Threading.Tasks.Task<string> SendCertRequestAsync(string packId, string certRequest) {
            return base.Channel.SendCertRequestAsync(packId, certRequest);
        }
        
        public string SendMobile(string id, string mobile) {
            return base.Channel.SendMobile(id, mobile);
        }
        
        public System.Threading.Tasks.Task<string> SendMobileAsync(string id, string mobile) {
            return base.Channel.SendMobileAsync(id, mobile);
        }
        
        public string Test(string file) {
            return base.Channel.Test(file);
        }
        
        public System.Threading.Tasks.Task<string> TestAsync(string file) {
            return base.Channel.TestAsync(file);
        }
        
        public string GetCemposRecipientList(string regionCode) {
            return base.Channel.GetCemposRecipientList(regionCode);
        }
        
        public System.Threading.Tasks.Task<string> GetCemposRecipientListAsync(string regionCode) {
            return base.Channel.GetCemposRecipientListAsync(regionCode);
        }
        
        public string GetRoutePfrList() {
            return base.Channel.GetRoutePfrList();
        }
        
        public System.Threading.Tasks.Task<string> GetRoutePfrListAsync() {
            return base.Channel.GetRoutePfrListAsync();
        }
        
        public string GetProductList(string login, string password) {
            return base.Channel.GetProductList(login, password);
        }
        
        public System.Threading.Tasks.Task<string> GetProductListAsync(string login, string password) {
            return base.Channel.GetProductListAsync(login, password);
        }
        
        public string GetWorkflowProductUidList(string workflowGuidsString) {
            return base.Channel.GetWorkflowProductUidList(workflowGuidsString);
        }
        
        public System.Threading.Tasks.Task<string> GetWorkflowProductUidListAsync(string workflowGuidsString) {
            return base.Channel.GetWorkflowProductUidListAsync(workflowGuidsString);
        }
        
        public string GetPfrLayoutCodes(string regionCode) {
            return base.Channel.GetPfrLayoutCodes(regionCode);
        }
        
        public System.Threading.Tasks.Task<string> GetPfrLayoutCodesAsync(string regionCode) {
            return base.Channel.GetPfrLayoutCodesAsync(regionCode);
        }
        
        public string GetFnsCodes(string regionCode) {
            return base.Channel.GetFnsCodes(regionCode);
        }
        
        public System.Threading.Tasks.Task<string> GetFnsCodesAsync(string regionCode) {
            return base.Channel.GetFnsCodesAsync(regionCode);
        }
        
        public string GetPfrCodes(string regionCode) {
            return base.Channel.GetPfrCodes(regionCode);
        }
        
        public System.Threading.Tasks.Task<string> GetPfrCodesAsync(string regionCode) {
            return base.Channel.GetPfrCodesAsync(regionCode);
        }
        
        public string GetStatCodes(string regionCode) {
            return base.Channel.GetStatCodes(regionCode);
        }
        
        public System.Threading.Tasks.Task<string> GetStatCodesAsync(string regionCode) {
            return base.Channel.GetStatCodesAsync(regionCode);
        }
        
        public string ReceiveResponse(string packetId) {
            return base.Channel.ReceiveResponse(packetId);
        }
        
        public System.Threading.Tasks.Task<string> ReceiveResponseAsync(string packetId) {
            return base.Channel.ReceiveResponseAsync(packetId);
        }
        
        public string GetPriceInfo(int priceTypeId) {
            return base.Channel.GetPriceInfo(priceTypeId);
        }
        
        public System.Threading.Tasks.Task<string> GetPriceInfoAsync(int priceTypeId) {
            return base.Channel.GetPriceInfoAsync(priceTypeId);
        }
        
        public string GetBgRequestList(string inn, string kpp) {
            return base.Channel.GetBgRequestList(inn, kpp);
        }
        
        public System.Threading.Tasks.Task<string> GetBgRequestListAsync(string inn, string kpp) {
            return base.Channel.GetBgRequestListAsync(inn, kpp);
        }
        
        public string GetHtmlFromCertificate(string cert, int template) {
            return base.Channel.GetHtmlFromCertificate(cert, template);
        }
        
        public System.Threading.Tasks.Task<string> GetHtmlFromCertificateAsync(string cert, int template) {
            return base.Channel.GetHtmlFromCertificateAsync(cert, template);
        }
        
        public string SignMessage(string id, string message) {
            return base.Channel.SignMessage(id, message);
        }
        
        public System.Threading.Tasks.Task<string> SignMessageAsync(string id, string message) {
            return base.Channel.SignMessageAsync(id, message);
        }
        
        public string EncryptMessage(string id, string message, string certificates) {
            return base.Channel.EncryptMessage(id, message, certificates);
        }
        
        public System.Threading.Tasks.Task<string> EncryptMessageAsync(string id, string message, string certificates) {
            return base.Channel.EncryptMessageAsync(id, message, certificates);
        }
        
        public string DecryptMessage(string id, string encryptedMessage) {
            return base.Channel.DecryptMessage(id, encryptedMessage);
        }
        
        public System.Threading.Tasks.Task<string> DecryptMessageAsync(string id, string encryptedMessage) {
            return base.Channel.DecryptMessageAsync(id, encryptedMessage);
        }
        
        public string GetSessionKey(string id, string password) {
            return base.Channel.GetSessionKey(id, password);
        }
        
        public System.Threading.Tasks.Task<string> GetSessionKeyAsync(string id, string password) {
            return base.Channel.GetSessionKeyAsync(id, password);
        }
        
        public string GetNpf(string id) {
            return base.Channel.GetNpf(id);
        }
        
        public System.Threading.Tasks.Task<string> GetNpfAsync(string id) {
            return base.Channel.GetNpfAsync(id);
        }
        
        public string VerifySign(string sign, string message) {
            return base.Channel.VerifySign(sign, message);
        }
        
        public System.Threading.Tasks.Task<string> VerifySignAsync(string sign, string message) {
            return base.Channel.VerifySignAsync(sign, message);
        }
        
        public string VerifyCert(string cert) {
            return base.Channel.VerifyCert(cert);
        }
        
        public System.Threading.Tasks.Task<string> VerifyCertAsync(string cert) {
            return base.Channel.VerifyCertAsync(cert);
        }
        
        public string SendTemplate(string template) {
            return base.Channel.SendTemplate(template);
        }
        
        public System.Threading.Tasks.Task<string> SendTemplateAsync(string template) {
            return base.Channel.SendTemplateAsync(template);
        }
        
        public string GetCryptoProTemplateOid() {
            return base.Channel.GetCryptoProTemplateOid();
        }
        
        public System.Threading.Tasks.Task<string> GetCryptoProTemplateOidAsync() {
            return base.Channel.GetCryptoProTemplateOidAsync();
        }
        
        public string GetCertificateSettings() {
            return base.Channel.GetCertificateSettings();
        }
        
        public System.Threading.Tasks.Task<string> GetCertificateSettingsAsync() {
            return base.Channel.GetCertificateSettingsAsync();
        }
    }
}
