//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moedelo.Finances.Tests {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Moedelo.Finances.Tests.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1CClientBankExchange
        ///ВерсияФормата=1.02
        ///Кодировка=Windows
        ///Отправитель=Cистема Авангард Интернет-Банк
        ///Получатель=Бухгалтерский учет, редакция 4.4
        ///ДатаНачала=01.10.2014
        ///ДатаКонца=02.10.2014
        ///РасчСчет=40802810727100015991
        ///СекцияРасчСчет
        ///ДатаНачала=01.10.2017
        ///ДатаКонца=02.11.2017
        ///РасчСчет=40802810727100015991
        ///НачальныйОстаток=884.42
        ///ВсегоПоступило=187541
        ///ВсегоСписано=177331.65
        ///КонечныйОстаток=11093.77
        ///КонецРасчСчет
        ///КонецДокумента.
        /// </summary>
        internal static string empty {
            get {
                return ResourceManager.GetString("empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1CClientBankExchange
        ///ВерсияФормата=1.02
        ///Кодировка=Windows
        ///Отправитель=Cистема Авангард Интернет-Банк
        ///Получатель=Бухгалтерский учет, редакция 4.4
        ///ДатаНачала=01.10.2014
        ///ДатаКонца=26.12.2014
        ///РасчСчет=40802810727100015991
        ///СекцияРасчСчет
        ///ДатаНачала=15.10.2017
        ///ДатаКонца=15.11.2017
        ///РасчСчет=40802810727100015991
        ///НачальныйОстаток=884.42
        ///ВсегоПоступило=187541
        ///ВсегоСписано=177331.65
        ///КонечныйОстаток=11093.77
        ///КонецРасчСчет
        ///СекцияДокумент=Платежное поручение
        ///Номер=2
        ///Дата=15.10.2017
        ///Сумма=10356
        ///ДатаСп [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string one_operation {
            get {
                return ResourceManager.GetString("one_operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1CClientBankExchange
        ///ВерсияФормата=1.02
        ///Кодировка=Windows
        ///Отправитель=Cистема Авангард Интернет-Банк
        ///Получатель=Бухгалтерский учет, редакция 4.4
        ///ДатаНачала=01.10.2014
        ///ДатаКонца=26.12.2014
        ///РасчСчет=40802810727100015991
        ///СекцияРасчСчет
        ///ДатаНачала=15.10.2017
        ///ДатаКонца=15.11.2017
        ///РасчСчет=40802810727100015991
        ///НачальныйОстаток=884.42
        ///ВсегоПоступило=187541
        ///ВсегоСписано=177331.65
        ///КонечныйОстаток=11093.77
        ///КонецРасчСчет
        ///
        ///СекцияДокумент=Банковский ордер
        ///Номер=866
        ///Дата=15.10.2017
        ///Сумма=99
        ///ДатаСпис [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string one_operation_commission {
            get {
                return ResourceManager.GetString("one_operation_commission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;PaymentOrder xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;Payer&gt;
        ///    &lt;Name&gt;Гномик&lt;/Name&gt;
        ///    &lt;Inn&gt;5837004553&lt;/Inn&gt;
        ///    &lt;Kpp&gt;111111111&lt;/Kpp&gt;
        ///    &lt;SettlementNumber&gt;40702810320090001124&lt;/SettlementNumber&gt;
        ///    &lt;BankName&gt;СЕВЕРО-ЗАПАДНЫЙ ФИЛИАЛ АО &quot;БАНК ИНТЕЗА&quot;&lt;/BankName&gt;
        ///    &lt;BankBik&gt;044030710&lt;/BankBik&gt;
        ///    &lt;BankCorrespondentAccount&gt;30101810100000000710&lt;/BankCorrespondentAccount&gt;
        ///    &lt;BankCity&gt;САНКТ-ПЕТЕРБУРГ&lt;/BankCity&gt;
        ///    &lt;IsOoo&gt;true&lt;/IsOoo&gt;        /// [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string payment_snapshot {
            get {
                return ResourceManager.GetString("payment_snapshot", resourceCulture);
            }
        }
    }
}
